servers:
  - address: "localhost"
    ip: "172.23.208.1"
    port: 40001
  - address: "localhost"
    ip: "172.23.208.1"
    port: 40002
robots:
  count: 10000
  tick: 10000 #毫秒
  login_interval : 200 #毫秒
loglevel: 1
