servers:
  - address: "localhost"
    ip: "172.23.208.1"
    port: 40006
  - address: "localhost"
    ip: "172.23.208.1"
    port: 40007
robots:
  count: 2000
  tick: 2000 #毫秒
  login_interval : 200 #毫秒
loglevel: 1
