// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/mysql_database_table.proto
// Protobuf C++ Version: 5.26.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_common_2fmysql_5fdatabase_5ftable_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_common_2fmysql_5fdatabase_5ftable_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "common/db_base.pb.h"
#include "common/user_accounts.pb.h"
#include "common/comp.pb.h"
#include "logic/component/player_scene_comp.pb.h"
#include "logic/component/actor_comp.pb.h"
#include "logic/component/player_comp.pb.h"
#include "logic/component/player_skill_comp.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_common_2fmysql_5fdatabase_5ftable_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2fmysql_5fdatabase_5ftable_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_common_2fmysql_5fdatabase_5ftable_2eproto;
class account_share_database;
struct account_share_databaseDefaultTypeInternal;
extern account_share_databaseDefaultTypeInternal _account_share_database_default_instance_;
class player_centre_database;
struct player_centre_databaseDefaultTypeInternal;
extern player_centre_databaseDefaultTypeInternal _player_centre_database_default_instance_;
class player_database;
struct player_databaseDefaultTypeInternal;
extern player_databaseDefaultTypeInternal _player_database_default_instance_;
class player_database_1;
struct player_database_1DefaultTypeInternal;
extern player_database_1DefaultTypeInternal _player_database_1_default_instance_;
class user_accounts;
struct user_accountsDefaultTypeInternal;
extern user_accountsDefaultTypeInternal _user_accounts_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class player_database_1 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:player_database_1) */ {
 public:
  inline player_database_1() : player_database_1(nullptr) {}
  ~player_database_1() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR player_database_1(
      ::google::protobuf::internal::ConstantInitialized);

  inline player_database_1(const player_database_1& from) : player_database_1(nullptr, from) {}
  inline player_database_1(player_database_1&& from) noexcept
      : player_database_1(nullptr, std::move(from)) {}
  inline player_database_1& operator=(const player_database_1& from) {
    CopyFrom(from);
    return *this;
  }
  inline player_database_1& operator=(player_database_1&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const player_database_1& default_instance() {
    return *internal_default_instance();
  }
  static inline const player_database_1* internal_default_instance() {
    return reinterpret_cast<const player_database_1*>(
        &_player_database_1_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(player_database_1& a, player_database_1& b) { a.Swap(&b); }
  inline void Swap(player_database_1* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(player_database_1* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  player_database_1* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<player_database_1>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const player_database_1& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const player_database_1& from) { player_database_1::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(player_database_1* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "player_database_1"; }

 protected:
  explicit player_database_1(::google::protobuf::Arena* arena);
  player_database_1(::google::protobuf::Arena* arena, const player_database_1& from);
  player_database_1(::google::protobuf::Arena* arena, player_database_1&& from) noexcept
      : player_database_1(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlayerIdFieldNumber = 1,
  };
  // uint64 player_id = 1;
  void clear_player_id() ;
  ::uint64_t player_id() const;
  void set_player_id(::uint64_t value);

  private:
  ::uint64_t _internal_player_id() const;
  void _internal_set_player_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:player_database_1)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::uint64_t player_id_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2fmysql_5fdatabase_5ftable_2eproto;
};
// -------------------------------------------------------------------

class account_share_database final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:account_share_database) */ {
 public:
  inline account_share_database() : account_share_database(nullptr) {}
  ~account_share_database() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR account_share_database(
      ::google::protobuf::internal::ConstantInitialized);

  inline account_share_database(const account_share_database& from) : account_share_database(nullptr, from) {}
  inline account_share_database(account_share_database&& from) noexcept
      : account_share_database(nullptr, std::move(from)) {}
  inline account_share_database& operator=(const account_share_database& from) {
    CopyFrom(from);
    return *this;
  }
  inline account_share_database& operator=(account_share_database&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const account_share_database& default_instance() {
    return *internal_default_instance();
  }
  static inline const account_share_database* internal_default_instance() {
    return reinterpret_cast<const account_share_database*>(
        &_account_share_database_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(account_share_database& a, account_share_database& b) { a.Swap(&b); }
  inline void Swap(account_share_database* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(account_share_database* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  account_share_database* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<account_share_database>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const account_share_database& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const account_share_database& from) { account_share_database::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(account_share_database* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "account_share_database"; }

 protected:
  explicit account_share_database(::google::protobuf::Arena* arena);
  account_share_database(::google::protobuf::Arena* arena, const account_share_database& from);
  account_share_database(::google::protobuf::Arena* arena, account_share_database&& from) noexcept
      : account_share_database(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAccountFieldNumber = 1,
  };
  // string account = 1;
  void clear_account() ;
  const std::string& account() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_account(Arg_&& arg, Args_... args);
  std::string* mutable_account();
  PROTOBUF_NODISCARD std::string* release_account();
  void set_allocated_account(std::string* value);

  private:
  const std::string& _internal_account() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_account(
      const std::string& value);
  std::string* _internal_mutable_account();

  public:
  // @@protoc_insertion_point(class_scope:account_share_database)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      38, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr account_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2fmysql_5fdatabase_5ftable_2eproto;
};
// -------------------------------------------------------------------

class user_accounts final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:user_accounts) */ {
 public:
  inline user_accounts() : user_accounts(nullptr) {}
  ~user_accounts() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR user_accounts(
      ::google::protobuf::internal::ConstantInitialized);

  inline user_accounts(const user_accounts& from) : user_accounts(nullptr, from) {}
  inline user_accounts(user_accounts&& from) noexcept
      : user_accounts(nullptr, std::move(from)) {}
  inline user_accounts& operator=(const user_accounts& from) {
    CopyFrom(from);
    return *this;
  }
  inline user_accounts& operator=(user_accounts&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const user_accounts& default_instance() {
    return *internal_default_instance();
  }
  static inline const user_accounts* internal_default_instance() {
    return reinterpret_cast<const user_accounts*>(
        &_user_accounts_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(user_accounts& a, user_accounts& b) { a.Swap(&b); }
  inline void Swap(user_accounts* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(user_accounts* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  user_accounts* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<user_accounts>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const user_accounts& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const user_accounts& from) { user_accounts::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(user_accounts* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "user_accounts"; }

 protected:
  explicit user_accounts(::google::protobuf::Arena* arena);
  user_accounts(::google::protobuf::Arena* arena, const user_accounts& from);
  user_accounts(::google::protobuf::Arena* arena, user_accounts&& from) noexcept
      : user_accounts(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAccountFieldNumber = 1,
    kPasswordFieldNumber = 2,
    kSimplePlayersFieldNumber = 3,
  };
  // string account = 1;
  void clear_account() ;
  const std::string& account() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_account(Arg_&& arg, Args_... args);
  std::string* mutable_account();
  PROTOBUF_NODISCARD std::string* release_account();
  void set_allocated_account(std::string* value);

  private:
  const std::string& _internal_account() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_account(
      const std::string& value);
  std::string* _internal_mutable_account();

  public:
  // string password = 2;
  void clear_password() ;
  const std::string& password() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_password(Arg_&& arg, Args_... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* value);

  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(
      const std::string& value);
  std::string* _internal_mutable_password();

  public:
  // .AccountSimplePlayerList simple_players = 3;
  bool has_simple_players() const;
  void clear_simple_players() ;
  const ::AccountSimplePlayerList& simple_players() const;
  PROTOBUF_NODISCARD ::AccountSimplePlayerList* release_simple_players();
  ::AccountSimplePlayerList* mutable_simple_players();
  void set_allocated_simple_players(::AccountSimplePlayerList* value);
  void unsafe_arena_set_allocated_simple_players(::AccountSimplePlayerList* value);
  ::AccountSimplePlayerList* unsafe_arena_release_simple_players();

  private:
  const ::AccountSimplePlayerList& _internal_simple_players() const;
  ::AccountSimplePlayerList* _internal_mutable_simple_players();

  public:
  // @@protoc_insertion_point(class_scope:user_accounts)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      37, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr account_;
    ::google::protobuf::internal::ArenaStringPtr password_;
    ::AccountSimplePlayerList* simple_players_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2fmysql_5fdatabase_5ftable_2eproto;
};
// -------------------------------------------------------------------

class player_database final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:player_database) */ {
 public:
  inline player_database() : player_database(nullptr) {}
  ~player_database() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR player_database(
      ::google::protobuf::internal::ConstantInitialized);

  inline player_database(const player_database& from) : player_database(nullptr, from) {}
  inline player_database(player_database&& from) noexcept
      : player_database(nullptr, std::move(from)) {}
  inline player_database& operator=(const player_database& from) {
    CopyFrom(from);
    return *this;
  }
  inline player_database& operator=(player_database&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const player_database& default_instance() {
    return *internal_default_instance();
  }
  static inline const player_database* internal_default_instance() {
    return reinterpret_cast<const player_database*>(
        &_player_database_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(player_database& a, player_database& b) { a.Swap(&b); }
  inline void Swap(player_database* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(player_database* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  player_database* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<player_database>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const player_database& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const player_database& from) { player_database::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(player_database* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "player_database"; }

 protected:
  explicit player_database(::google::protobuf::Arena* arena);
  player_database(::google::protobuf::Arena* arena, const player_database& from);
  player_database(::google::protobuf::Arena* arena, player_database&& from) noexcept
      : player_database(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTransformFieldNumber = 2,
    kUint64PbComponentFieldNumber = 3,
    kSkillListFieldNumber = 4,
    kUint32PbComponentFieldNumber = 5,
    kDerivedAttributesComponentFieldNumber = 6,
    kLevelComponentFieldNumber = 7,
    kPlayerIdFieldNumber = 1,
  };
  // .Transform transform = 2;
  bool has_transform() const;
  void clear_transform() ;
  const ::Transform& transform() const;
  PROTOBUF_NODISCARD ::Transform* release_transform();
  ::Transform* mutable_transform();
  void set_allocated_transform(::Transform* value);
  void unsafe_arena_set_allocated_transform(::Transform* value);
  ::Transform* unsafe_arena_release_transform();

  private:
  const ::Transform& _internal_transform() const;
  ::Transform* _internal_mutable_transform();

  public:
  // .PlayerUint64PBComponent uint64_pb_component = 3;
  bool has_uint64_pb_component() const;
  void clear_uint64_pb_component() ;
  const ::PlayerUint64PBComponent& uint64_pb_component() const;
  PROTOBUF_NODISCARD ::PlayerUint64PBComponent* release_uint64_pb_component();
  ::PlayerUint64PBComponent* mutable_uint64_pb_component();
  void set_allocated_uint64_pb_component(::PlayerUint64PBComponent* value);
  void unsafe_arena_set_allocated_uint64_pb_component(::PlayerUint64PBComponent* value);
  ::PlayerUint64PBComponent* unsafe_arena_release_uint64_pb_component();

  private:
  const ::PlayerUint64PBComponent& _internal_uint64_pb_component() const;
  ::PlayerUint64PBComponent* _internal_mutable_uint64_pb_component();

  public:
  // .PlayerSkillListPBComponent skill_list = 4;
  bool has_skill_list() const;
  void clear_skill_list() ;
  const ::PlayerSkillListPBComponent& skill_list() const;
  PROTOBUF_NODISCARD ::PlayerSkillListPBComponent* release_skill_list();
  ::PlayerSkillListPBComponent* mutable_skill_list();
  void set_allocated_skill_list(::PlayerSkillListPBComponent* value);
  void unsafe_arena_set_allocated_skill_list(::PlayerSkillListPBComponent* value);
  ::PlayerSkillListPBComponent* unsafe_arena_release_skill_list();

  private:
  const ::PlayerSkillListPBComponent& _internal_skill_list() const;
  ::PlayerSkillListPBComponent* _internal_mutable_skill_list();

  public:
  // .PlayerUint32PBComponent uint32_pb_component = 5;
  bool has_uint32_pb_component() const;
  void clear_uint32_pb_component() ;
  const ::PlayerUint32PBComponent& uint32_pb_component() const;
  PROTOBUF_NODISCARD ::PlayerUint32PBComponent* release_uint32_pb_component();
  ::PlayerUint32PBComponent* mutable_uint32_pb_component();
  void set_allocated_uint32_pb_component(::PlayerUint32PBComponent* value);
  void unsafe_arena_set_allocated_uint32_pb_component(::PlayerUint32PBComponent* value);
  ::PlayerUint32PBComponent* unsafe_arena_release_uint32_pb_component();

  private:
  const ::PlayerUint32PBComponent& _internal_uint32_pb_component() const;
  ::PlayerUint32PBComponent* _internal_mutable_uint32_pb_component();

  public:
  // .BaseAttributesPBComponent derived_attributes_component = 6;
  bool has_derived_attributes_component() const;
  void clear_derived_attributes_component() ;
  const ::BaseAttributesPBComponent& derived_attributes_component() const;
  PROTOBUF_NODISCARD ::BaseAttributesPBComponent* release_derived_attributes_component();
  ::BaseAttributesPBComponent* mutable_derived_attributes_component();
  void set_allocated_derived_attributes_component(::BaseAttributesPBComponent* value);
  void unsafe_arena_set_allocated_derived_attributes_component(::BaseAttributesPBComponent* value);
  ::BaseAttributesPBComponent* unsafe_arena_release_derived_attributes_component();

  private:
  const ::BaseAttributesPBComponent& _internal_derived_attributes_component() const;
  ::BaseAttributesPBComponent* _internal_mutable_derived_attributes_component();

  public:
  // .LevelComponent level_component = 7;
  bool has_level_component() const;
  void clear_level_component() ;
  const ::LevelComponent& level_component() const;
  PROTOBUF_NODISCARD ::LevelComponent* release_level_component();
  ::LevelComponent* mutable_level_component();
  void set_allocated_level_component(::LevelComponent* value);
  void unsafe_arena_set_allocated_level_component(::LevelComponent* value);
  ::LevelComponent* unsafe_arena_release_level_component();

  private:
  const ::LevelComponent& _internal_level_component() const;
  ::LevelComponent* _internal_mutable_level_component();

  public:
  // uint64 player_id = 1;
  void clear_player_id() ;
  ::uint64_t player_id() const;
  void set_player_id(::uint64_t value);

  private:
  ::uint64_t _internal_player_id() const;
  void _internal_set_player_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:player_database)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 6,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::Transform* transform_;
    ::PlayerUint64PBComponent* uint64_pb_component_;
    ::PlayerSkillListPBComponent* skill_list_;
    ::PlayerUint32PBComponent* uint32_pb_component_;
    ::BaseAttributesPBComponent* derived_attributes_component_;
    ::LevelComponent* level_component_;
    ::uint64_t player_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2fmysql_5fdatabase_5ftable_2eproto;
};
// -------------------------------------------------------------------

class player_centre_database final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:player_centre_database) */ {
 public:
  inline player_centre_database() : player_centre_database(nullptr) {}
  ~player_centre_database() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR player_centre_database(
      ::google::protobuf::internal::ConstantInitialized);

  inline player_centre_database(const player_centre_database& from) : player_centre_database(nullptr, from) {}
  inline player_centre_database(player_centre_database&& from) noexcept
      : player_centre_database(nullptr, std::move(from)) {}
  inline player_centre_database& operator=(const player_centre_database& from) {
    CopyFrom(from);
    return *this;
  }
  inline player_centre_database& operator=(player_centre_database&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const player_centre_database& default_instance() {
    return *internal_default_instance();
  }
  static inline const player_centre_database* internal_default_instance() {
    return reinterpret_cast<const player_centre_database*>(
        &_player_centre_database_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(player_centre_database& a, player_centre_database& b) { a.Swap(&b); }
  inline void Swap(player_centre_database* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(player_centre_database* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  player_centre_database* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<player_centre_database>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const player_centre_database& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const player_centre_database& from) { player_centre_database::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(player_centre_database* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "player_centre_database"; }

 protected:
  explicit player_centre_database(::google::protobuf::Arena* arena);
  player_centre_database(::google::protobuf::Arena* arena, const player_centre_database& from);
  player_centre_database(::google::protobuf::Arena* arena, player_centre_database&& from) noexcept
      : player_centre_database(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSceneInfoFieldNumber = 2,
    kPlayerIdFieldNumber = 1,
  };
  // .PlayerSceneContextPBComponent scene_info = 2;
  bool has_scene_info() const;
  void clear_scene_info() ;
  const ::PlayerSceneContextPBComponent& scene_info() const;
  PROTOBUF_NODISCARD ::PlayerSceneContextPBComponent* release_scene_info();
  ::PlayerSceneContextPBComponent* mutable_scene_info();
  void set_allocated_scene_info(::PlayerSceneContextPBComponent* value);
  void unsafe_arena_set_allocated_scene_info(::PlayerSceneContextPBComponent* value);
  ::PlayerSceneContextPBComponent* unsafe_arena_release_scene_info();

  private:
  const ::PlayerSceneContextPBComponent& _internal_scene_info() const;
  ::PlayerSceneContextPBComponent* _internal_mutable_scene_info();

  public:
  // uint64 player_id = 1;
  void clear_player_id() ;
  ::uint64_t player_id() const;
  void set_player_id(::uint64_t value);

  private:
  ::uint64_t _internal_player_id() const;
  void _internal_set_player_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:player_centre_database)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::PlayerSceneContextPBComponent* scene_info_;
    ::uint64_t player_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2fmysql_5fdatabase_5ftable_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// user_accounts

// string account = 1;
inline void user_accounts::clear_account() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.account_.ClearToEmpty();
}
inline const std::string& user_accounts::account() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:user_accounts.account)
  return _internal_account();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void user_accounts::set_account(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.account_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:user_accounts.account)
}
inline std::string* user_accounts::mutable_account() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_account();
  // @@protoc_insertion_point(field_mutable:user_accounts.account)
  return _s;
}
inline const std::string& user_accounts::_internal_account() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.account_.Get();
}
inline void user_accounts::_internal_set_account(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.account_.Set(value, GetArena());
}
inline std::string* user_accounts::_internal_mutable_account() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.account_.Mutable( GetArena());
}
inline std::string* user_accounts::release_account() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:user_accounts.account)
  return _impl_.account_.Release();
}
inline void user_accounts::set_allocated_account(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.account_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.account_.IsDefault()) {
          _impl_.account_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:user_accounts.account)
}

// string password = 2;
inline void user_accounts::clear_password() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.password_.ClearToEmpty();
}
inline const std::string& user_accounts::password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:user_accounts.password)
  return _internal_password();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void user_accounts::set_password(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.password_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:user_accounts.password)
}
inline std::string* user_accounts::mutable_password() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:user_accounts.password)
  return _s;
}
inline const std::string& user_accounts::_internal_password() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.password_.Get();
}
inline void user_accounts::_internal_set_password(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.password_.Set(value, GetArena());
}
inline std::string* user_accounts::_internal_mutable_password() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.password_.Mutable( GetArena());
}
inline std::string* user_accounts::release_password() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:user_accounts.password)
  return _impl_.password_.Release();
}
inline void user_accounts::set_allocated_password(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.password_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.password_.IsDefault()) {
          _impl_.password_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:user_accounts.password)
}

// .AccountSimplePlayerList simple_players = 3;
inline bool user_accounts::has_simple_players() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.simple_players_ != nullptr);
  return value;
}
inline const ::AccountSimplePlayerList& user_accounts::_internal_simple_players() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::AccountSimplePlayerList* p = _impl_.simple_players_;
  return p != nullptr ? *p : reinterpret_cast<const ::AccountSimplePlayerList&>(::_AccountSimplePlayerList_default_instance_);
}
inline const ::AccountSimplePlayerList& user_accounts::simple_players() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:user_accounts.simple_players)
  return _internal_simple_players();
}
inline void user_accounts::unsafe_arena_set_allocated_simple_players(::AccountSimplePlayerList* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.simple_players_);
  }
  _impl_.simple_players_ = reinterpret_cast<::AccountSimplePlayerList*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:user_accounts.simple_players)
}
inline ::AccountSimplePlayerList* user_accounts::release_simple_players() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::AccountSimplePlayerList* released = _impl_.simple_players_;
  _impl_.simple_players_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::AccountSimplePlayerList* user_accounts::unsafe_arena_release_simple_players() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:user_accounts.simple_players)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::AccountSimplePlayerList* temp = _impl_.simple_players_;
  _impl_.simple_players_ = nullptr;
  return temp;
}
inline ::AccountSimplePlayerList* user_accounts::_internal_mutable_simple_players() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.simple_players_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::AccountSimplePlayerList>(GetArena());
    _impl_.simple_players_ = reinterpret_cast<::AccountSimplePlayerList*>(p);
  }
  return _impl_.simple_players_;
}
inline ::AccountSimplePlayerList* user_accounts::mutable_simple_players() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::AccountSimplePlayerList* _msg = _internal_mutable_simple_players();
  // @@protoc_insertion_point(field_mutable:user_accounts.simple_players)
  return _msg;
}
inline void user_accounts::set_allocated_simple_players(::AccountSimplePlayerList* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.simple_players_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.simple_players_ = reinterpret_cast<::AccountSimplePlayerList*>(value);
  // @@protoc_insertion_point(field_set_allocated:user_accounts.simple_players)
}

// -------------------------------------------------------------------

// account_share_database

// string account = 1;
inline void account_share_database::clear_account() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.account_.ClearToEmpty();
}
inline const std::string& account_share_database::account() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:account_share_database.account)
  return _internal_account();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void account_share_database::set_account(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.account_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:account_share_database.account)
}
inline std::string* account_share_database::mutable_account() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_account();
  // @@protoc_insertion_point(field_mutable:account_share_database.account)
  return _s;
}
inline const std::string& account_share_database::_internal_account() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.account_.Get();
}
inline void account_share_database::_internal_set_account(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.account_.Set(value, GetArena());
}
inline std::string* account_share_database::_internal_mutable_account() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.account_.Mutable( GetArena());
}
inline std::string* account_share_database::release_account() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:account_share_database.account)
  return _impl_.account_.Release();
}
inline void account_share_database::set_allocated_account(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.account_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.account_.IsDefault()) {
          _impl_.account_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:account_share_database.account)
}

// -------------------------------------------------------------------

// player_centre_database

// uint64 player_id = 1;
inline void player_centre_database::clear_player_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.player_id_ = ::uint64_t{0u};
}
inline ::uint64_t player_centre_database::player_id() const {
  // @@protoc_insertion_point(field_get:player_centre_database.player_id)
  return _internal_player_id();
}
inline void player_centre_database::set_player_id(::uint64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:player_centre_database.player_id)
}
inline ::uint64_t player_centre_database::_internal_player_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.player_id_;
}
inline void player_centre_database::_internal_set_player_id(::uint64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.player_id_ = value;
}

// .PlayerSceneContextPBComponent scene_info = 2;
inline bool player_centre_database::has_scene_info() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.scene_info_ != nullptr);
  return value;
}
inline const ::PlayerSceneContextPBComponent& player_centre_database::_internal_scene_info() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::PlayerSceneContextPBComponent* p = _impl_.scene_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::PlayerSceneContextPBComponent&>(::_PlayerSceneContextPBComponent_default_instance_);
}
inline const ::PlayerSceneContextPBComponent& player_centre_database::scene_info() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:player_centre_database.scene_info)
  return _internal_scene_info();
}
inline void player_centre_database::unsafe_arena_set_allocated_scene_info(::PlayerSceneContextPBComponent* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.scene_info_);
  }
  _impl_.scene_info_ = reinterpret_cast<::PlayerSceneContextPBComponent*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:player_centre_database.scene_info)
}
inline ::PlayerSceneContextPBComponent* player_centre_database::release_scene_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PlayerSceneContextPBComponent* released = _impl_.scene_info_;
  _impl_.scene_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::PlayerSceneContextPBComponent* player_centre_database::unsafe_arena_release_scene_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:player_centre_database.scene_info)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PlayerSceneContextPBComponent* temp = _impl_.scene_info_;
  _impl_.scene_info_ = nullptr;
  return temp;
}
inline ::PlayerSceneContextPBComponent* player_centre_database::_internal_mutable_scene_info() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.scene_info_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::PlayerSceneContextPBComponent>(GetArena());
    _impl_.scene_info_ = reinterpret_cast<::PlayerSceneContextPBComponent*>(p);
  }
  return _impl_.scene_info_;
}
inline ::PlayerSceneContextPBComponent* player_centre_database::mutable_scene_info() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::PlayerSceneContextPBComponent* _msg = _internal_mutable_scene_info();
  // @@protoc_insertion_point(field_mutable:player_centre_database.scene_info)
  return _msg;
}
inline void player_centre_database::set_allocated_scene_info(::PlayerSceneContextPBComponent* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.scene_info_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.scene_info_ = reinterpret_cast<::PlayerSceneContextPBComponent*>(value);
  // @@protoc_insertion_point(field_set_allocated:player_centre_database.scene_info)
}

// -------------------------------------------------------------------

// player_database

// uint64 player_id = 1;
inline void player_database::clear_player_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.player_id_ = ::uint64_t{0u};
}
inline ::uint64_t player_database::player_id() const {
  // @@protoc_insertion_point(field_get:player_database.player_id)
  return _internal_player_id();
}
inline void player_database::set_player_id(::uint64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:player_database.player_id)
}
inline ::uint64_t player_database::_internal_player_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.player_id_;
}
inline void player_database::_internal_set_player_id(::uint64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.player_id_ = value;
}

// .Transform transform = 2;
inline bool player_database::has_transform() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.transform_ != nullptr);
  return value;
}
inline const ::Transform& player_database::_internal_transform() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::Transform* p = _impl_.transform_;
  return p != nullptr ? *p : reinterpret_cast<const ::Transform&>(::_Transform_default_instance_);
}
inline const ::Transform& player_database::transform() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:player_database.transform)
  return _internal_transform();
}
inline void player_database::unsafe_arena_set_allocated_transform(::Transform* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.transform_);
  }
  _impl_.transform_ = reinterpret_cast<::Transform*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:player_database.transform)
}
inline ::Transform* player_database::release_transform() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Transform* released = _impl_.transform_;
  _impl_.transform_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::Transform* player_database::unsafe_arena_release_transform() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:player_database.transform)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Transform* temp = _impl_.transform_;
  _impl_.transform_ = nullptr;
  return temp;
}
inline ::Transform* player_database::_internal_mutable_transform() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.transform_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Transform>(GetArena());
    _impl_.transform_ = reinterpret_cast<::Transform*>(p);
  }
  return _impl_.transform_;
}
inline ::Transform* player_database::mutable_transform() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Transform* _msg = _internal_mutable_transform();
  // @@protoc_insertion_point(field_mutable:player_database.transform)
  return _msg;
}
inline void player_database::set_allocated_transform(::Transform* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.transform_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.transform_ = reinterpret_cast<::Transform*>(value);
  // @@protoc_insertion_point(field_set_allocated:player_database.transform)
}

// .PlayerUint64PBComponent uint64_pb_component = 3;
inline bool player_database::has_uint64_pb_component() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.uint64_pb_component_ != nullptr);
  return value;
}
inline const ::PlayerUint64PBComponent& player_database::_internal_uint64_pb_component() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::PlayerUint64PBComponent* p = _impl_.uint64_pb_component_;
  return p != nullptr ? *p : reinterpret_cast<const ::PlayerUint64PBComponent&>(::_PlayerUint64PBComponent_default_instance_);
}
inline const ::PlayerUint64PBComponent& player_database::uint64_pb_component() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:player_database.uint64_pb_component)
  return _internal_uint64_pb_component();
}
inline void player_database::unsafe_arena_set_allocated_uint64_pb_component(::PlayerUint64PBComponent* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.uint64_pb_component_);
  }
  _impl_.uint64_pb_component_ = reinterpret_cast<::PlayerUint64PBComponent*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:player_database.uint64_pb_component)
}
inline ::PlayerUint64PBComponent* player_database::release_uint64_pb_component() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::PlayerUint64PBComponent* released = _impl_.uint64_pb_component_;
  _impl_.uint64_pb_component_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::PlayerUint64PBComponent* player_database::unsafe_arena_release_uint64_pb_component() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:player_database.uint64_pb_component)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::PlayerUint64PBComponent* temp = _impl_.uint64_pb_component_;
  _impl_.uint64_pb_component_ = nullptr;
  return temp;
}
inline ::PlayerUint64PBComponent* player_database::_internal_mutable_uint64_pb_component() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.uint64_pb_component_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::PlayerUint64PBComponent>(GetArena());
    _impl_.uint64_pb_component_ = reinterpret_cast<::PlayerUint64PBComponent*>(p);
  }
  return _impl_.uint64_pb_component_;
}
inline ::PlayerUint64PBComponent* player_database::mutable_uint64_pb_component() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::PlayerUint64PBComponent* _msg = _internal_mutable_uint64_pb_component();
  // @@protoc_insertion_point(field_mutable:player_database.uint64_pb_component)
  return _msg;
}
inline void player_database::set_allocated_uint64_pb_component(::PlayerUint64PBComponent* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.uint64_pb_component_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.uint64_pb_component_ = reinterpret_cast<::PlayerUint64PBComponent*>(value);
  // @@protoc_insertion_point(field_set_allocated:player_database.uint64_pb_component)
}

// .PlayerSkillListPBComponent skill_list = 4;
inline bool player_database::has_skill_list() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.skill_list_ != nullptr);
  return value;
}
inline const ::PlayerSkillListPBComponent& player_database::_internal_skill_list() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::PlayerSkillListPBComponent* p = _impl_.skill_list_;
  return p != nullptr ? *p : reinterpret_cast<const ::PlayerSkillListPBComponent&>(::_PlayerSkillListPBComponent_default_instance_);
}
inline const ::PlayerSkillListPBComponent& player_database::skill_list() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:player_database.skill_list)
  return _internal_skill_list();
}
inline void player_database::unsafe_arena_set_allocated_skill_list(::PlayerSkillListPBComponent* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.skill_list_);
  }
  _impl_.skill_list_ = reinterpret_cast<::PlayerSkillListPBComponent*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:player_database.skill_list)
}
inline ::PlayerSkillListPBComponent* player_database::release_skill_list() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::PlayerSkillListPBComponent* released = _impl_.skill_list_;
  _impl_.skill_list_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::PlayerSkillListPBComponent* player_database::unsafe_arena_release_skill_list() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:player_database.skill_list)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::PlayerSkillListPBComponent* temp = _impl_.skill_list_;
  _impl_.skill_list_ = nullptr;
  return temp;
}
inline ::PlayerSkillListPBComponent* player_database::_internal_mutable_skill_list() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.skill_list_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::PlayerSkillListPBComponent>(GetArena());
    _impl_.skill_list_ = reinterpret_cast<::PlayerSkillListPBComponent*>(p);
  }
  return _impl_.skill_list_;
}
inline ::PlayerSkillListPBComponent* player_database::mutable_skill_list() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::PlayerSkillListPBComponent* _msg = _internal_mutable_skill_list();
  // @@protoc_insertion_point(field_mutable:player_database.skill_list)
  return _msg;
}
inline void player_database::set_allocated_skill_list(::PlayerSkillListPBComponent* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.skill_list_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.skill_list_ = reinterpret_cast<::PlayerSkillListPBComponent*>(value);
  // @@protoc_insertion_point(field_set_allocated:player_database.skill_list)
}

// .PlayerUint32PBComponent uint32_pb_component = 5;
inline bool player_database::has_uint32_pb_component() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.uint32_pb_component_ != nullptr);
  return value;
}
inline const ::PlayerUint32PBComponent& player_database::_internal_uint32_pb_component() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::PlayerUint32PBComponent* p = _impl_.uint32_pb_component_;
  return p != nullptr ? *p : reinterpret_cast<const ::PlayerUint32PBComponent&>(::_PlayerUint32PBComponent_default_instance_);
}
inline const ::PlayerUint32PBComponent& player_database::uint32_pb_component() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:player_database.uint32_pb_component)
  return _internal_uint32_pb_component();
}
inline void player_database::unsafe_arena_set_allocated_uint32_pb_component(::PlayerUint32PBComponent* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.uint32_pb_component_);
  }
  _impl_.uint32_pb_component_ = reinterpret_cast<::PlayerUint32PBComponent*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:player_database.uint32_pb_component)
}
inline ::PlayerUint32PBComponent* player_database::release_uint32_pb_component() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::PlayerUint32PBComponent* released = _impl_.uint32_pb_component_;
  _impl_.uint32_pb_component_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::PlayerUint32PBComponent* player_database::unsafe_arena_release_uint32_pb_component() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:player_database.uint32_pb_component)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::PlayerUint32PBComponent* temp = _impl_.uint32_pb_component_;
  _impl_.uint32_pb_component_ = nullptr;
  return temp;
}
inline ::PlayerUint32PBComponent* player_database::_internal_mutable_uint32_pb_component() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.uint32_pb_component_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::PlayerUint32PBComponent>(GetArena());
    _impl_.uint32_pb_component_ = reinterpret_cast<::PlayerUint32PBComponent*>(p);
  }
  return _impl_.uint32_pb_component_;
}
inline ::PlayerUint32PBComponent* player_database::mutable_uint32_pb_component() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::PlayerUint32PBComponent* _msg = _internal_mutable_uint32_pb_component();
  // @@protoc_insertion_point(field_mutable:player_database.uint32_pb_component)
  return _msg;
}
inline void player_database::set_allocated_uint32_pb_component(::PlayerUint32PBComponent* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.uint32_pb_component_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.uint32_pb_component_ = reinterpret_cast<::PlayerUint32PBComponent*>(value);
  // @@protoc_insertion_point(field_set_allocated:player_database.uint32_pb_component)
}

// .BaseAttributesPBComponent derived_attributes_component = 6;
inline bool player_database::has_derived_attributes_component() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.derived_attributes_component_ != nullptr);
  return value;
}
inline const ::BaseAttributesPBComponent& player_database::_internal_derived_attributes_component() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::BaseAttributesPBComponent* p = _impl_.derived_attributes_component_;
  return p != nullptr ? *p : reinterpret_cast<const ::BaseAttributesPBComponent&>(::_BaseAttributesPBComponent_default_instance_);
}
inline const ::BaseAttributesPBComponent& player_database::derived_attributes_component() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:player_database.derived_attributes_component)
  return _internal_derived_attributes_component();
}
inline void player_database::unsafe_arena_set_allocated_derived_attributes_component(::BaseAttributesPBComponent* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.derived_attributes_component_);
  }
  _impl_.derived_attributes_component_ = reinterpret_cast<::BaseAttributesPBComponent*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:player_database.derived_attributes_component)
}
inline ::BaseAttributesPBComponent* player_database::release_derived_attributes_component() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::BaseAttributesPBComponent* released = _impl_.derived_attributes_component_;
  _impl_.derived_attributes_component_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::BaseAttributesPBComponent* player_database::unsafe_arena_release_derived_attributes_component() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:player_database.derived_attributes_component)

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::BaseAttributesPBComponent* temp = _impl_.derived_attributes_component_;
  _impl_.derived_attributes_component_ = nullptr;
  return temp;
}
inline ::BaseAttributesPBComponent* player_database::_internal_mutable_derived_attributes_component() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.derived_attributes_component_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::BaseAttributesPBComponent>(GetArena());
    _impl_.derived_attributes_component_ = reinterpret_cast<::BaseAttributesPBComponent*>(p);
  }
  return _impl_.derived_attributes_component_;
}
inline ::BaseAttributesPBComponent* player_database::mutable_derived_attributes_component() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000010u;
  ::BaseAttributesPBComponent* _msg = _internal_mutable_derived_attributes_component();
  // @@protoc_insertion_point(field_mutable:player_database.derived_attributes_component)
  return _msg;
}
inline void player_database::set_allocated_derived_attributes_component(::BaseAttributesPBComponent* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.derived_attributes_component_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }

  _impl_.derived_attributes_component_ = reinterpret_cast<::BaseAttributesPBComponent*>(value);
  // @@protoc_insertion_point(field_set_allocated:player_database.derived_attributes_component)
}

// .LevelComponent level_component = 7;
inline bool player_database::has_level_component() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.level_component_ != nullptr);
  return value;
}
inline const ::LevelComponent& player_database::_internal_level_component() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::LevelComponent* p = _impl_.level_component_;
  return p != nullptr ? *p : reinterpret_cast<const ::LevelComponent&>(::_LevelComponent_default_instance_);
}
inline const ::LevelComponent& player_database::level_component() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:player_database.level_component)
  return _internal_level_component();
}
inline void player_database::unsafe_arena_set_allocated_level_component(::LevelComponent* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.level_component_);
  }
  _impl_.level_component_ = reinterpret_cast<::LevelComponent*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:player_database.level_component)
}
inline ::LevelComponent* player_database::release_level_component() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000020u;
  ::LevelComponent* released = _impl_.level_component_;
  _impl_.level_component_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::LevelComponent* player_database::unsafe_arena_release_level_component() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:player_database.level_component)

  _impl_._has_bits_[0] &= ~0x00000020u;
  ::LevelComponent* temp = _impl_.level_component_;
  _impl_.level_component_ = nullptr;
  return temp;
}
inline ::LevelComponent* player_database::_internal_mutable_level_component() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.level_component_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::LevelComponent>(GetArena());
    _impl_.level_component_ = reinterpret_cast<::LevelComponent*>(p);
  }
  return _impl_.level_component_;
}
inline ::LevelComponent* player_database::mutable_level_component() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000020u;
  ::LevelComponent* _msg = _internal_mutable_level_component();
  // @@protoc_insertion_point(field_mutable:player_database.level_component)
  return _msg;
}
inline void player_database::set_allocated_level_component(::LevelComponent* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.level_component_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }

  _impl_.level_component_ = reinterpret_cast<::LevelComponent*>(value);
  // @@protoc_insertion_point(field_set_allocated:player_database.level_component)
}

// -------------------------------------------------------------------

// player_database_1

// uint64 player_id = 1;
inline void player_database_1::clear_player_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.player_id_ = ::uint64_t{0u};
}
inline ::uint64_t player_database_1::player_id() const {
  // @@protoc_insertion_point(field_get:player_database_1.player_id)
  return _internal_player_id();
}
inline void player_database_1::set_player_id(::uint64_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:player_database_1.player_id)
}
inline ::uint64_t player_database_1::_internal_player_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.player_id_;
}
inline void player_database_1::_internal_set_player_id(::uint64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.player_id_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_common_2fmysql_5fdatabase_5ftable_2eproto_2epb_2eh
