#ifndef MASTER_SERVER_SRC_MASTER_PLAYER_MASTER_PLAYER_H_
#define MASTER_SERVER_SRC_MASTER_PLAYER_MASTER_PLAYER_H_

namespace master
{

}//namespace master

#endif//MASTER_SERVER_SRC_MASTER_PLAYER_MASTER_PLAYER_H_
