#ifndef COMMON_SRC_GAME_LOGIC_MISSIONS_CONDITION_H_
#define COMMON_SRC_GAME_LOGIC_MISSIONS_CONDITION_H_

namespace common
{


}//namespace common

#endif // !COMMON_SRC_GAME_LOGIC_MISSIONS_CONDITION_H_
