// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: proto/common/component/buff_comp.proto

package component

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuffContextComp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DamageValue   float32                `protobuf:"fixed32,1,opt,name=damage_value,json=damageValue,proto3" json:"damage_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuffContextComp) Reset() {
	*x = BuffContextComp{}
	mi := &file_proto_common_component_buff_comp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuffContextComp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuffContextComp) ProtoMessage() {}

func (x *BuffContextComp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_buff_comp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuffContextComp.ProtoReflect.Descriptor instead.
func (*BuffContextComp) Descriptor() ([]byte, []int) {
	return file_proto_common_component_buff_comp_proto_rawDescGZIP(), []int{0}
}

func (x *BuffContextComp) GetDamageValue() float32 {
	if x != nil {
		return x.DamageValue
	}
	return 0
}

type BuffPeriodicBuffComp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeriodicTimer float64                `protobuf:"fixed64,1,opt,name=periodic_timer,json=periodicTimer,proto3" json:"periodic_timer,omitempty"`
	TicksDone     uint32                 `protobuf:"varint,2,opt,name=ticks_done,json=ticksDone,proto3" json:"ticks_done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuffPeriodicBuffComp) Reset() {
	*x = BuffPeriodicBuffComp{}
	mi := &file_proto_common_component_buff_comp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuffPeriodicBuffComp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuffPeriodicBuffComp) ProtoMessage() {}

func (x *BuffPeriodicBuffComp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_buff_comp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuffPeriodicBuffComp.ProtoReflect.Descriptor instead.
func (*BuffPeriodicBuffComp) Descriptor() ([]byte, []int) {
	return file_proto_common_component_buff_comp_proto_rawDescGZIP(), []int{1}
}

func (x *BuffPeriodicBuffComp) GetPeriodicTimer() float64 {
	if x != nil {
		return x.PeriodicTimer
	}
	return 0
}

func (x *BuffPeriodicBuffComp) GetTicksDone() uint32 {
	if x != nil {
		return x.TicksDone
	}
	return 0
}

type BuffComp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BuffId          uint64                 `protobuf:"varint,1,opt,name=buff_id,json=buffId,proto3" json:"buff_id,omitempty"`
	BuffTableId     uint32                 `protobuf:"varint,2,opt,name=buff_table_id,json=buffTableId,proto3" json:"buff_table_id,omitempty"`
	AbilityId       uint32                 `protobuf:"varint,3,opt,name=ability_id,json=abilityId,proto3" json:"ability_id,omitempty"`
	ParentEntity    uint64                 `protobuf:"varint,4,opt,name=parent_entity,json=parentEntity,proto3" json:"parent_entity,omitempty"`
	Layer           uint32                 `protobuf:"varint,5,opt,name=layer,proto3" json:"layer,omitempty"`
	Caster          uint64                 `protobuf:"varint,6,opt,name=caster,proto3" json:"caster,omitempty"`
	Triggerdamage   bool                   `protobuf:"varint,7,opt,name=triggerdamage,proto3" json:"triggerdamage,omitempty"`
	ProcessedCaster uint64                 `protobuf:"varint,8,opt,name=processed_caster,json=processedCaster,proto3" json:"processed_caster,omitempty"` // Caster after table processing
	Data            []byte                 `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`                                               // Various buff type data
	Periodic        *BuffPeriodicBuffComp  `protobuf:"bytes,10,opt,name=periodic,proto3" json:"periodic,omitempty"`
	SubBuffListId   map[uint64]bool        `protobuf:"bytes,11,rep,name=sub_buff_list_id,json=subBuffListId,proto3" json:"sub_buff_list_id,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	HasAddedSubBuff bool                   `protobuf:"varint,12,opt,name=has_added_sub_buff,json=hasAddedSubBuff,proto3" json:"has_added_sub_buff,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BuffComp) Reset() {
	*x = BuffComp{}
	mi := &file_proto_common_component_buff_comp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuffComp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuffComp) ProtoMessage() {}

func (x *BuffComp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_buff_comp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuffComp.ProtoReflect.Descriptor instead.
func (*BuffComp) Descriptor() ([]byte, []int) {
	return file_proto_common_component_buff_comp_proto_rawDescGZIP(), []int{2}
}

func (x *BuffComp) GetBuffId() uint64 {
	if x != nil {
		return x.BuffId
	}
	return 0
}

func (x *BuffComp) GetBuffTableId() uint32 {
	if x != nil {
		return x.BuffTableId
	}
	return 0
}

func (x *BuffComp) GetAbilityId() uint32 {
	if x != nil {
		return x.AbilityId
	}
	return 0
}

func (x *BuffComp) GetParentEntity() uint64 {
	if x != nil {
		return x.ParentEntity
	}
	return 0
}

func (x *BuffComp) GetLayer() uint32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *BuffComp) GetCaster() uint64 {
	if x != nil {
		return x.Caster
	}
	return 0
}

func (x *BuffComp) GetTriggerdamage() bool {
	if x != nil {
		return x.Triggerdamage
	}
	return false
}

func (x *BuffComp) GetProcessedCaster() uint64 {
	if x != nil {
		return x.ProcessedCaster
	}
	return 0
}

func (x *BuffComp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BuffComp) GetPeriodic() *BuffPeriodicBuffComp {
	if x != nil {
		return x.Periodic
	}
	return nil
}

func (x *BuffComp) GetSubBuffListId() map[uint64]bool {
	if x != nil {
		return x.SubBuffListId
	}
	return nil
}

func (x *BuffComp) GetHasAddedSubBuff() bool {
	if x != nil {
		return x.HasAddedSubBuff
	}
	return false
}

type DamageEventComp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       uint64                 `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	AttackerId    uint64                 `protobuf:"varint,2,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	Target        uint64                 `protobuf:"varint,3,opt,name=target,proto3" json:"target,omitempty"`
	Damage        float64                `protobuf:"fixed64,4,opt,name=damage,proto3" json:"damage,omitempty"`
	DamageType    uint32                 `protobuf:"varint,5,opt,name=damage_type,json=damageType,proto3" json:"damage_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DamageEventComp) Reset() {
	*x = DamageEventComp{}
	mi := &file_proto_common_component_buff_comp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DamageEventComp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DamageEventComp) ProtoMessage() {}

func (x *DamageEventComp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_buff_comp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DamageEventComp.ProtoReflect.Descriptor instead.
func (*DamageEventComp) Descriptor() ([]byte, []int) {
	return file_proto_common_component_buff_comp_proto_rawDescGZIP(), []int{3}
}

func (x *DamageEventComp) GetSkillId() uint64 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *DamageEventComp) GetAttackerId() uint64 {
	if x != nil {
		return x.AttackerId
	}
	return 0
}

func (x *DamageEventComp) GetTarget() uint64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *DamageEventComp) GetDamage() float64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *DamageEventComp) GetDamageType() uint32 {
	if x != nil {
		return x.DamageType
	}
	return 0
}

type BuffNoDamageOrSkillHitInLastSecondsComp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastTime      uint64                 `protobuf:"varint,1,opt,name=last_time,json=lastTime,proto3" json:"last_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuffNoDamageOrSkillHitInLastSecondsComp) Reset() {
	*x = BuffNoDamageOrSkillHitInLastSecondsComp{}
	mi := &file_proto_common_component_buff_comp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuffNoDamageOrSkillHitInLastSecondsComp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuffNoDamageOrSkillHitInLastSecondsComp) ProtoMessage() {}

func (x *BuffNoDamageOrSkillHitInLastSecondsComp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_buff_comp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuffNoDamageOrSkillHitInLastSecondsComp.ProtoReflect.Descriptor instead.
func (*BuffNoDamageOrSkillHitInLastSecondsComp) Descriptor() ([]byte, []int) {
	return file_proto_common_component_buff_comp_proto_rawDescGZIP(), []int{4}
}

func (x *BuffNoDamageOrSkillHitInLastSecondsComp) GetLastTime() uint64 {
	if x != nil {
		return x.LastTime
	}
	return 0
}

var File_proto_common_component_buff_comp_proto protoreflect.FileDescriptor

const file_proto_common_component_buff_comp_proto_rawDesc = "" +
	"\n" +
	"&proto/common/component/buff_comp.proto\"4\n" +
	"\x0fBuffContextComp\x12!\n" +
	"\fdamage_value\x18\x01 \x01(\x02R\vdamageValue\"\\\n" +
	"\x14BuffPeriodicBuffComp\x12%\n" +
	"\x0eperiodic_timer\x18\x01 \x01(\x01R\rperiodicTimer\x12\x1d\n" +
	"\n" +
	"ticks_done\x18\x02 \x01(\rR\tticksDone\"\x87\x04\n" +
	"\bBuffComp\x12\x17\n" +
	"\abuff_id\x18\x01 \x01(\x04R\x06buffId\x12\"\n" +
	"\rbuff_table_id\x18\x02 \x01(\rR\vbuffTableId\x12\x1d\n" +
	"\n" +
	"ability_id\x18\x03 \x01(\rR\tabilityId\x12#\n" +
	"\rparent_entity\x18\x04 \x01(\x04R\fparentEntity\x12\x14\n" +
	"\x05layer\x18\x05 \x01(\rR\x05layer\x12\x16\n" +
	"\x06caster\x18\x06 \x01(\x04R\x06caster\x12$\n" +
	"\rtriggerdamage\x18\a \x01(\bR\rtriggerdamage\x12)\n" +
	"\x10processed_caster\x18\b \x01(\x04R\x0fprocessedCaster\x12\x12\n" +
	"\x04data\x18\t \x01(\fR\x04data\x121\n" +
	"\bperiodic\x18\n" +
	" \x01(\v2\x15.BuffPeriodicBuffCompR\bperiodic\x12E\n" +
	"\x10sub_buff_list_id\x18\v \x03(\v2\x1c.BuffComp.SubBuffListIdEntryR\rsubBuffListId\x12+\n" +
	"\x12has_added_sub_buff\x18\f \x01(\bR\x0fhasAddedSubBuff\x1a@\n" +
	"\x12SubBuffListIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x0fDamageEventComp\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x04R\askillId\x12\x1f\n" +
	"\vattacker_id\x18\x02 \x01(\x04R\n" +
	"attackerId\x12\x16\n" +
	"\x06target\x18\x03 \x01(\x04R\x06target\x12\x16\n" +
	"\x06damage\x18\x04 \x01(\x01R\x06damage\x12\x1f\n" +
	"\vdamage_type\x18\x05 \x01(\rR\n" +
	"damageType\"F\n" +
	"'BuffNoDamageOrSkillHitInLastSecondsComp\x12\x1b\n" +
	"\tlast_time\x18\x01 \x01(\x04R\blastTimeB\x1fZ\x1dcommon/proto/common/componentb\x06proto3"

var (
	file_proto_common_component_buff_comp_proto_rawDescOnce sync.Once
	file_proto_common_component_buff_comp_proto_rawDescData []byte
)

func file_proto_common_component_buff_comp_proto_rawDescGZIP() []byte {
	file_proto_common_component_buff_comp_proto_rawDescOnce.Do(func() {
		file_proto_common_component_buff_comp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_component_buff_comp_proto_rawDesc), len(file_proto_common_component_buff_comp_proto_rawDesc)))
	})
	return file_proto_common_component_buff_comp_proto_rawDescData
}

var file_proto_common_component_buff_comp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_common_component_buff_comp_proto_goTypes = []any{
	(*BuffContextComp)(nil),                         // 0: BuffContextComp
	(*BuffPeriodicBuffComp)(nil),                    // 1: BuffPeriodicBuffComp
	(*BuffComp)(nil),                                // 2: BuffComp
	(*DamageEventComp)(nil),                         // 3: DamageEventComp
	(*BuffNoDamageOrSkillHitInLastSecondsComp)(nil), // 4: BuffNoDamageOrSkillHitInLastSecondsComp
	nil, // 5: BuffComp.SubBuffListIdEntry
}
var file_proto_common_component_buff_comp_proto_depIdxs = []int32{
	1, // 0: BuffComp.periodic:type_name -> BuffPeriodicBuffComp
	5, // 1: BuffComp.sub_buff_list_id:type_name -> BuffComp.SubBuffListIdEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_common_component_buff_comp_proto_init() }
func file_proto_common_component_buff_comp_proto_init() {
	if File_proto_common_component_buff_comp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_component_buff_comp_proto_rawDesc), len(file_proto_common_component_buff_comp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_component_buff_comp_proto_goTypes,
		DependencyIndexes: file_proto_common_component_buff_comp_proto_depIdxs,
		MessageInfos:      file_proto_common_component_buff_comp_proto_msgTypes,
	}.Build()
	File_proto_common_component_buff_comp_proto = out.File
	file_proto_common_component_buff_comp_proto_goTypes = nil
	file_proto_common_component_buff_comp_proto_depIdxs = nil
}
