// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testmultikey_config.proto
// Protobuf C++ Version: 5.26.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_testmultikey_5fconfig_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_testmultikey_5fconfig_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_testmultikey_5fconfig_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_testmultikey_5fconfig_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_testmultikey_5fconfig_2eproto;
class TestMultiKeyTable;
struct TestMultiKeyTableDefaultTypeInternal;
extern TestMultiKeyTableDefaultTypeInternal _TestMultiKeyTable_default_instance_;
class TestMultiKeyTable_Immunetag1Entry_DoNotUse;
struct TestMultiKeyTable_Immunetag1Entry_DoNotUseDefaultTypeInternal;
extern TestMultiKeyTable_Immunetag1Entry_DoNotUseDefaultTypeInternal _TestMultiKeyTable_Immunetag1Entry_DoNotUse_default_instance_;
class TestMultiKeyTable_Tag1Entry_DoNotUse;
struct TestMultiKeyTable_Tag1Entry_DoNotUseDefaultTypeInternal;
extern TestMultiKeyTable_Tag1Entry_DoNotUseDefaultTypeInternal _TestMultiKeyTable_Tag1Entry_DoNotUse_default_instance_;
class TestMultiKeyTabledData;
struct TestMultiKeyTabledDataDefaultTypeInternal;
extern TestMultiKeyTabledDataDefaultTypeInternal _TestMultiKeyTabledData_default_instance_;
class immunetag1;
struct immunetag1DefaultTypeInternal;
extern immunetag1DefaultTypeInternal _immunetag1_default_instance_;
class tag1;
struct tag1DefaultTypeInternal;
extern tag1DefaultTypeInternal _tag1_default_instance_;
class testobj1;
struct testobj1DefaultTypeInternal;
extern testobj1DefaultTypeInternal _testobj1_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class testobj1 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:testobj1) */ {
 public:
  inline testobj1() : testobj1(nullptr) {}
  ~testobj1() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR testobj1(
      ::google::protobuf::internal::ConstantInitialized);

  inline testobj1(const testobj1& from) : testobj1(nullptr, from) {}
  inline testobj1(testobj1&& from) noexcept
      : testobj1(nullptr, std::move(from)) {}
  inline testobj1& operator=(const testobj1& from) {
    CopyFrom(from);
    return *this;
  }
  inline testobj1& operator=(testobj1&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const testobj1& default_instance() {
    return *internal_default_instance();
  }
  static inline const testobj1* internal_default_instance() {
    return reinterpret_cast<const testobj1*>(
        &_testobj1_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(testobj1& a, testobj1& b) { a.Swap(&b); }
  inline void Swap(testobj1* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(testobj1* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  testobj1* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<testobj1>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const testobj1& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const testobj1& from) { testobj1::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(testobj1* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "testobj1"; }

 protected:
  explicit testobj1(::google::protobuf::Arena* arena);
  testobj1(::google::protobuf::Arena* arena, const testobj1& from);
  testobj1(::google::protobuf::Arena* arena, testobj1&& from) noexcept
      : testobj1(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTestobj1KeyFieldNumber = 1,
    kTestobj1ValueFieldNumber = 2,
  };
  // uint32 testobj1_key = 1;
  void clear_testobj1_key() ;
  ::uint32_t testobj1_key() const;
  void set_testobj1_key(::uint32_t value);

  private:
  ::uint32_t _internal_testobj1_key() const;
  void _internal_set_testobj1_key(::uint32_t value);

  public:
  // uint32 testobj1_value = 2;
  void clear_testobj1_value() ;
  ::uint32_t testobj1_value() const;
  void set_testobj1_value(::uint32_t value);

  private:
  ::uint32_t _internal_testobj1_value() const;
  void _internal_set_testobj1_value(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:testobj1)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::uint32_t testobj1_key_;
    ::uint32_t testobj1_value_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_testmultikey_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class tag1 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:tag1) */ {
 public:
  inline tag1() : tag1(nullptr) {}
  ~tag1() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR tag1(
      ::google::protobuf::internal::ConstantInitialized);

  inline tag1(const tag1& from) : tag1(nullptr, from) {}
  inline tag1(tag1&& from) noexcept
      : tag1(nullptr, std::move(from)) {}
  inline tag1& operator=(const tag1& from) {
    CopyFrom(from);
    return *this;
  }
  inline tag1& operator=(tag1&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const tag1& default_instance() {
    return *internal_default_instance();
  }
  static inline const tag1* internal_default_instance() {
    return reinterpret_cast<const tag1*>(
        &_tag1_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(tag1& a, tag1& b) { a.Swap(&b); }
  inline void Swap(tag1* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(tag1* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  tag1* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<tag1>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const tag1& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const tag1& from) { tag1::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(tag1* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "tag1"; }

 protected:
  explicit tag1(::google::protobuf::Arena* arena);
  tag1(::google::protobuf::Arena* arena, const tag1& from);
  tag1(::google::protobuf::Arena* arena, tag1&& from) noexcept
      : tag1(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTag1KeyFieldNumber = 1,
    kTag1ValueFieldNumber = 2,
  };
  // string tag1_key = 1;
  void clear_tag1_key() ;
  const std::string& tag1_key() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_tag1_key(Arg_&& arg, Args_... args);
  std::string* mutable_tag1_key();
  PROTOBUF_NODISCARD std::string* release_tag1_key();
  void set_allocated_tag1_key(std::string* value);

  private:
  const std::string& _internal_tag1_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tag1_key(
      const std::string& value);
  std::string* _internal_mutable_tag1_key();

  public:
  // string tag1_value = 2;
  void clear_tag1_value() ;
  const std::string& tag1_value() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_tag1_value(Arg_&& arg, Args_... args);
  std::string* mutable_tag1_value();
  PROTOBUF_NODISCARD std::string* release_tag1_value();
  void set_allocated_tag1_value(std::string* value);

  private:
  const std::string& _internal_tag1_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tag1_value(
      const std::string& value);
  std::string* _internal_mutable_tag1_value();

  public:
  // @@protoc_insertion_point(class_scope:tag1)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      31, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr tag1_key_;
    ::google::protobuf::internal::ArenaStringPtr tag1_value_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_testmultikey_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class immunetag1 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:immunetag1) */ {
 public:
  inline immunetag1() : immunetag1(nullptr) {}
  ~immunetag1() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR immunetag1(
      ::google::protobuf::internal::ConstantInitialized);

  inline immunetag1(const immunetag1& from) : immunetag1(nullptr, from) {}
  inline immunetag1(immunetag1&& from) noexcept
      : immunetag1(nullptr, std::move(from)) {}
  inline immunetag1& operator=(const immunetag1& from) {
    CopyFrom(from);
    return *this;
  }
  inline immunetag1& operator=(immunetag1&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const immunetag1& default_instance() {
    return *internal_default_instance();
  }
  static inline const immunetag1* internal_default_instance() {
    return reinterpret_cast<const immunetag1*>(
        &_immunetag1_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(immunetag1& a, immunetag1& b) { a.Swap(&b); }
  inline void Swap(immunetag1* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(immunetag1* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  immunetag1* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<immunetag1>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const immunetag1& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const immunetag1& from) { immunetag1::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(immunetag1* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "immunetag1"; }

 protected:
  explicit immunetag1(::google::protobuf::Arena* arena);
  immunetag1(::google::protobuf::Arena* arena, const immunetag1& from);
  immunetag1(::google::protobuf::Arena* arena, immunetag1&& from) noexcept
      : immunetag1(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kImmunetag1KeyFieldNumber = 1,
    kImmunetag1ValueFieldNumber = 2,
  };
  // string immunetag1_key = 1;
  void clear_immunetag1_key() ;
  const std::string& immunetag1_key() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_immunetag1_key(Arg_&& arg, Args_... args);
  std::string* mutable_immunetag1_key();
  PROTOBUF_NODISCARD std::string* release_immunetag1_key();
  void set_allocated_immunetag1_key(std::string* value);

  private:
  const std::string& _internal_immunetag1_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_immunetag1_key(
      const std::string& value);
  std::string* _internal_mutable_immunetag1_key();

  public:
  // string immunetag1_value = 2;
  void clear_immunetag1_value() ;
  const std::string& immunetag1_value() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_immunetag1_value(Arg_&& arg, Args_... args);
  std::string* mutable_immunetag1_value();
  PROTOBUF_NODISCARD std::string* release_immunetag1_value();
  void set_allocated_immunetag1_value(std::string* value);

  private:
  const std::string& _internal_immunetag1_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_immunetag1_value(
      const std::string& value);
  std::string* _internal_mutable_immunetag1_value();

  public:
  // @@protoc_insertion_point(class_scope:immunetag1)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      49, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr immunetag1_key_;
    ::google::protobuf::internal::ArenaStringPtr immunetag1_value_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_testmultikey_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class TestMultiKeyTable_Tag1Entry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          TestMultiKeyTable_Tag1Entry_DoNotUse, std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      TestMultiKeyTable_Tag1Entry_DoNotUse, std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  TestMultiKeyTable_Tag1Entry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TestMultiKeyTable_Tag1Entry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit TestMultiKeyTable_Tag1Entry_DoNotUse(::google::protobuf::Arena* arena);
  static const TestMultiKeyTable_Tag1Entry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const TestMultiKeyTable_Tag1Entry_DoNotUse*>(
        &_TestMultiKeyTable_Tag1Entry_DoNotUse_default_instance_);
  }
  static bool ValidateKey(std::string* s) {
    return ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::google::protobuf::internal::WireFormatLite::PARSE, "TestMultiKeyTable.Tag1Entry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::google::protobuf::internal::WireFormatLite::PARSE, "TestMultiKeyTable.Tag1Entry.value");
 }
  ::google::protobuf::Metadata GetMetadata() const final;
  friend struct ::TableStruct_testmultikey_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class TestMultiKeyTable_Immunetag1Entry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          TestMultiKeyTable_Immunetag1Entry_DoNotUse, std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      TestMultiKeyTable_Immunetag1Entry_DoNotUse, std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  TestMultiKeyTable_Immunetag1Entry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TestMultiKeyTable_Immunetag1Entry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit TestMultiKeyTable_Immunetag1Entry_DoNotUse(::google::protobuf::Arena* arena);
  static const TestMultiKeyTable_Immunetag1Entry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const TestMultiKeyTable_Immunetag1Entry_DoNotUse*>(
        &_TestMultiKeyTable_Immunetag1Entry_DoNotUse_default_instance_);
  }
  static bool ValidateKey(std::string* s) {
    return ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::google::protobuf::internal::WireFormatLite::PARSE, "TestMultiKeyTable.Immunetag1Entry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::google::protobuf::internal::WireFormatLite::PARSE, "TestMultiKeyTable.Immunetag1Entry.value");
 }
  ::google::protobuf::Metadata GetMetadata() const final;
  friend struct ::TableStruct_testmultikey_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class TestMultiKeyTable final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:TestMultiKeyTable) */ {
 public:
  inline TestMultiKeyTable() : TestMultiKeyTable(nullptr) {}
  ~TestMultiKeyTable() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TestMultiKeyTable(
      ::google::protobuf::internal::ConstantInitialized);

  inline TestMultiKeyTable(const TestMultiKeyTable& from) : TestMultiKeyTable(nullptr, from) {}
  inline TestMultiKeyTable(TestMultiKeyTable&& from) noexcept
      : TestMultiKeyTable(nullptr, std::move(from)) {}
  inline TestMultiKeyTable& operator=(const TestMultiKeyTable& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestMultiKeyTable& operator=(TestMultiKeyTable&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestMultiKeyTable& default_instance() {
    return *internal_default_instance();
  }
  static inline const TestMultiKeyTable* internal_default_instance() {
    return reinterpret_cast<const TestMultiKeyTable*>(
        &_TestMultiKeyTable_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(TestMultiKeyTable& a, TestMultiKeyTable& b) { a.Swap(&b); }
  inline void Swap(TestMultiKeyTable* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestMultiKeyTable* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestMultiKeyTable* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<TestMultiKeyTable>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TestMultiKeyTable& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TestMultiKeyTable& from) { TestMultiKeyTable::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(TestMultiKeyTable* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "TestMultiKeyTable"; }

 protected:
  explicit TestMultiKeyTable(::google::protobuf::Arena* arena);
  TestMultiKeyTable(::google::protobuf::Arena* arena, const TestMultiKeyTable& from);
  TestMultiKeyTable(::google::protobuf::Arena* arena, TestMultiKeyTable&& from) noexcept
      : TestMultiKeyTable(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTag1FieldNumber = 2,
    kImmunetag1FieldNumber = 3,
    kTestobj1FieldNumber = 5,
    kEffectFieldNumber = 6,
    kStringkeyFieldNumber = 7,
    kMstringkeyFieldNumber = 10,
    kIdFieldNumber = 1,
    kLevelFieldNumber = 4,
    kUint32KeyFieldNumber = 8,
    kIn32KeyFieldNumber = 9,
    kMuint32KeyFieldNumber = 11,
    kMin32KeyFieldNumber = 12,
  };
  // map<string, string> tag1 = 2;
  int tag1_size() const;
  private:
  int _internal_tag1_size() const;

  public:
  void clear_tag1() ;
  const ::google::protobuf::Map<std::string, std::string>& tag1() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_tag1();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_tag1() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_tag1();

  public:
  // map<string, string> immunetag1 = 3;
  int immunetag1_size() const;
  private:
  int _internal_immunetag1_size() const;

  public:
  void clear_immunetag1() ;
  const ::google::protobuf::Map<std::string, std::string>& immunetag1() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_immunetag1();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_immunetag1() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_immunetag1();

  public:
  // repeated .testobj1 testobj1 = 5;
  int testobj1_size() const;
  private:
  int _internal_testobj1_size() const;

  public:
  void clear_testobj1() ;
  ::testobj1* mutable_testobj1(int index);
  ::google::protobuf::RepeatedPtrField<::testobj1>* mutable_testobj1();

  private:
  const ::google::protobuf::RepeatedPtrField<::testobj1>& _internal_testobj1() const;
  ::google::protobuf::RepeatedPtrField<::testobj1>* _internal_mutable_testobj1();
  public:
  const ::testobj1& testobj1(int index) const;
  ::testobj1* add_testobj1();
  const ::google::protobuf::RepeatedPtrField<::testobj1>& testobj1() const;
  // repeated uint32 effect = 6;
  int effect_size() const;
  private:
  int _internal_effect_size() const;

  public:
  void clear_effect() ;
  ::uint32_t effect(int index) const;
  void set_effect(int index, ::uint32_t value);
  void add_effect(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& effect() const;
  ::google::protobuf::RepeatedField<::uint32_t>* mutable_effect();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_effect() const;
  ::google::protobuf::RepeatedField<::uint32_t>* _internal_mutable_effect();

  public:
  // string stringkey = 7;
  void clear_stringkey() ;
  const std::string& stringkey() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_stringkey(Arg_&& arg, Args_... args);
  std::string* mutable_stringkey();
  PROTOBUF_NODISCARD std::string* release_stringkey();
  void set_allocated_stringkey(std::string* value);

  private:
  const std::string& _internal_stringkey() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stringkey(
      const std::string& value);
  std::string* _internal_mutable_stringkey();

  public:
  // string mstringkey = 10;
  void clear_mstringkey() ;
  const std::string& mstringkey() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_mstringkey(Arg_&& arg, Args_... args);
  std::string* mutable_mstringkey();
  PROTOBUF_NODISCARD std::string* release_mstringkey();
  void set_allocated_mstringkey(std::string* value);

  private:
  const std::string& _internal_mstringkey() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_mstringkey(
      const std::string& value);
  std::string* _internal_mutable_mstringkey();

  public:
  // uint32 id = 1;
  void clear_id() ;
  ::uint32_t id() const;
  void set_id(::uint32_t value);

  private:
  ::uint32_t _internal_id() const;
  void _internal_set_id(::uint32_t value);

  public:
  // uint32 level = 4;
  void clear_level() ;
  ::uint32_t level() const;
  void set_level(::uint32_t value);

  private:
  ::uint32_t _internal_level() const;
  void _internal_set_level(::uint32_t value);

  public:
  // uint32 uint32key = 8;
  void clear_uint32key() ;
  ::uint32_t uint32key() const;
  void set_uint32key(::uint32_t value);

  private:
  ::uint32_t _internal_uint32key() const;
  void _internal_set_uint32key(::uint32_t value);

  public:
  // int32 in32key = 9;
  void clear_in32key() ;
  ::int32_t in32key() const;
  void set_in32key(::int32_t value);

  private:
  ::int32_t _internal_in32key() const;
  void _internal_set_in32key(::int32_t value);

  public:
  // uint32 muint32key = 11;
  void clear_muint32key() ;
  ::uint32_t muint32key() const;
  void set_muint32key(::uint32_t value);

  private:
  ::uint32_t _internal_muint32key() const;
  void _internal_set_muint32key(::uint32_t value);

  public:
  // int32 min32key = 12;
  void clear_min32key() ;
  ::int32_t min32key() const;
  void set_min32key(::int32_t value);

  private:
  ::int32_t _internal_min32key() const;
  void _internal_set_min32key(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:TestMultiKeyTable)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 12, 3,
      67, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::MapField<TestMultiKeyTable_Tag1Entry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        tag1_;
    ::google::protobuf::internal::MapField<TestMultiKeyTable_Immunetag1Entry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        immunetag1_;
    ::google::protobuf::RepeatedPtrField< ::testobj1 > testobj1_;
    ::google::protobuf::RepeatedField<::uint32_t> effect_;
    mutable ::google::protobuf::internal::CachedSize _effect_cached_byte_size_;
    ::google::protobuf::internal::ArenaStringPtr stringkey_;
    ::google::protobuf::internal::ArenaStringPtr mstringkey_;
    ::uint32_t id_;
    ::uint32_t level_;
    ::uint32_t uint32key_;
    ::int32_t in32key_;
    ::uint32_t muint32key_;
    ::int32_t min32key_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_testmultikey_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class TestMultiKeyTabledData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:TestMultiKeyTabledData) */ {
 public:
  inline TestMultiKeyTabledData() : TestMultiKeyTabledData(nullptr) {}
  ~TestMultiKeyTabledData() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TestMultiKeyTabledData(
      ::google::protobuf::internal::ConstantInitialized);

  inline TestMultiKeyTabledData(const TestMultiKeyTabledData& from) : TestMultiKeyTabledData(nullptr, from) {}
  inline TestMultiKeyTabledData(TestMultiKeyTabledData&& from) noexcept
      : TestMultiKeyTabledData(nullptr, std::move(from)) {}
  inline TestMultiKeyTabledData& operator=(const TestMultiKeyTabledData& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestMultiKeyTabledData& operator=(TestMultiKeyTabledData&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestMultiKeyTabledData& default_instance() {
    return *internal_default_instance();
  }
  static inline const TestMultiKeyTabledData* internal_default_instance() {
    return reinterpret_cast<const TestMultiKeyTabledData*>(
        &_TestMultiKeyTabledData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(TestMultiKeyTabledData& a, TestMultiKeyTabledData& b) { a.Swap(&b); }
  inline void Swap(TestMultiKeyTabledData* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestMultiKeyTabledData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestMultiKeyTabledData* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<TestMultiKeyTabledData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TestMultiKeyTabledData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TestMultiKeyTabledData& from) { TestMultiKeyTabledData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(TestMultiKeyTabledData* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "TestMultiKeyTabledData"; }

 protected:
  explicit TestMultiKeyTabledData(::google::protobuf::Arena* arena);
  TestMultiKeyTabledData(::google::protobuf::Arena* arena, const TestMultiKeyTabledData& from);
  TestMultiKeyTabledData(::google::protobuf::Arena* arena, TestMultiKeyTabledData&& from) noexcept
      : TestMultiKeyTabledData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 1,
  };
  // repeated .TestMultiKeyTable data = 1;
  int data_size() const;
  private:
  int _internal_data_size() const;

  public:
  void clear_data() ;
  ::TestMultiKeyTable* mutable_data(int index);
  ::google::protobuf::RepeatedPtrField<::TestMultiKeyTable>* mutable_data();

  private:
  const ::google::protobuf::RepeatedPtrField<::TestMultiKeyTable>& _internal_data() const;
  ::google::protobuf::RepeatedPtrField<::TestMultiKeyTable>* _internal_mutable_data();
  public:
  const ::TestMultiKeyTable& data(int index) const;
  ::TestMultiKeyTable* add_data();
  const ::google::protobuf::RepeatedPtrField<::TestMultiKeyTable>& data() const;
  // @@protoc_insertion_point(class_scope:TestMultiKeyTabledData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::TestMultiKeyTable > data_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_testmultikey_5fconfig_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// tag1

// string tag1_key = 1;
inline void tag1::clear_tag1_key() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tag1_key_.ClearToEmpty();
}
inline const std::string& tag1::tag1_key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:tag1.tag1_key)
  return _internal_tag1_key();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void tag1::set_tag1_key(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tag1_key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:tag1.tag1_key)
}
inline std::string* tag1::mutable_tag1_key() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_tag1_key();
  // @@protoc_insertion_point(field_mutable:tag1.tag1_key)
  return _s;
}
inline const std::string& tag1::_internal_tag1_key() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.tag1_key_.Get();
}
inline void tag1::_internal_set_tag1_key(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tag1_key_.Set(value, GetArena());
}
inline std::string* tag1::_internal_mutable_tag1_key() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.tag1_key_.Mutable( GetArena());
}
inline std::string* tag1::release_tag1_key() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:tag1.tag1_key)
  return _impl_.tag1_key_.Release();
}
inline void tag1::set_allocated_tag1_key(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tag1_key_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.tag1_key_.IsDefault()) {
          _impl_.tag1_key_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tag1.tag1_key)
}

// string tag1_value = 2;
inline void tag1::clear_tag1_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tag1_value_.ClearToEmpty();
}
inline const std::string& tag1::tag1_value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:tag1.tag1_value)
  return _internal_tag1_value();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void tag1::set_tag1_value(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tag1_value_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:tag1.tag1_value)
}
inline std::string* tag1::mutable_tag1_value() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_tag1_value();
  // @@protoc_insertion_point(field_mutable:tag1.tag1_value)
  return _s;
}
inline const std::string& tag1::_internal_tag1_value() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.tag1_value_.Get();
}
inline void tag1::_internal_set_tag1_value(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tag1_value_.Set(value, GetArena());
}
inline std::string* tag1::_internal_mutable_tag1_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.tag1_value_.Mutable( GetArena());
}
inline std::string* tag1::release_tag1_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:tag1.tag1_value)
  return _impl_.tag1_value_.Release();
}
inline void tag1::set_allocated_tag1_value(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tag1_value_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.tag1_value_.IsDefault()) {
          _impl_.tag1_value_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tag1.tag1_value)
}

// -------------------------------------------------------------------

// immunetag1

// string immunetag1_key = 1;
inline void immunetag1::clear_immunetag1_key() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.immunetag1_key_.ClearToEmpty();
}
inline const std::string& immunetag1::immunetag1_key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:immunetag1.immunetag1_key)
  return _internal_immunetag1_key();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void immunetag1::set_immunetag1_key(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.immunetag1_key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:immunetag1.immunetag1_key)
}
inline std::string* immunetag1::mutable_immunetag1_key() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_immunetag1_key();
  // @@protoc_insertion_point(field_mutable:immunetag1.immunetag1_key)
  return _s;
}
inline const std::string& immunetag1::_internal_immunetag1_key() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.immunetag1_key_.Get();
}
inline void immunetag1::_internal_set_immunetag1_key(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.immunetag1_key_.Set(value, GetArena());
}
inline std::string* immunetag1::_internal_mutable_immunetag1_key() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.immunetag1_key_.Mutable( GetArena());
}
inline std::string* immunetag1::release_immunetag1_key() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:immunetag1.immunetag1_key)
  return _impl_.immunetag1_key_.Release();
}
inline void immunetag1::set_allocated_immunetag1_key(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.immunetag1_key_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.immunetag1_key_.IsDefault()) {
          _impl_.immunetag1_key_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:immunetag1.immunetag1_key)
}

// string immunetag1_value = 2;
inline void immunetag1::clear_immunetag1_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.immunetag1_value_.ClearToEmpty();
}
inline const std::string& immunetag1::immunetag1_value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:immunetag1.immunetag1_value)
  return _internal_immunetag1_value();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void immunetag1::set_immunetag1_value(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.immunetag1_value_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:immunetag1.immunetag1_value)
}
inline std::string* immunetag1::mutable_immunetag1_value() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_immunetag1_value();
  // @@protoc_insertion_point(field_mutable:immunetag1.immunetag1_value)
  return _s;
}
inline const std::string& immunetag1::_internal_immunetag1_value() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.immunetag1_value_.Get();
}
inline void immunetag1::_internal_set_immunetag1_value(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.immunetag1_value_.Set(value, GetArena());
}
inline std::string* immunetag1::_internal_mutable_immunetag1_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.immunetag1_value_.Mutable( GetArena());
}
inline std::string* immunetag1::release_immunetag1_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:immunetag1.immunetag1_value)
  return _impl_.immunetag1_value_.Release();
}
inline void immunetag1::set_allocated_immunetag1_value(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.immunetag1_value_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.immunetag1_value_.IsDefault()) {
          _impl_.immunetag1_value_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:immunetag1.immunetag1_value)
}

// -------------------------------------------------------------------

// testobj1

// uint32 testobj1_key = 1;
inline void testobj1::clear_testobj1_key() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.testobj1_key_ = 0u;
}
inline ::uint32_t testobj1::testobj1_key() const {
  // @@protoc_insertion_point(field_get:testobj1.testobj1_key)
  return _internal_testobj1_key();
}
inline void testobj1::set_testobj1_key(::uint32_t value) {
  _internal_set_testobj1_key(value);
  // @@protoc_insertion_point(field_set:testobj1.testobj1_key)
}
inline ::uint32_t testobj1::_internal_testobj1_key() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.testobj1_key_;
}
inline void testobj1::_internal_set_testobj1_key(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.testobj1_key_ = value;
}

// uint32 testobj1_value = 2;
inline void testobj1::clear_testobj1_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.testobj1_value_ = 0u;
}
inline ::uint32_t testobj1::testobj1_value() const {
  // @@protoc_insertion_point(field_get:testobj1.testobj1_value)
  return _internal_testobj1_value();
}
inline void testobj1::set_testobj1_value(::uint32_t value) {
  _internal_set_testobj1_value(value);
  // @@protoc_insertion_point(field_set:testobj1.testobj1_value)
}
inline ::uint32_t testobj1::_internal_testobj1_value() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.testobj1_value_;
}
inline void testobj1::_internal_set_testobj1_value(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.testobj1_value_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// TestMultiKeyTable

// uint32 id = 1;
inline void TestMultiKeyTable::clear_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.id_ = 0u;
}
inline ::uint32_t TestMultiKeyTable::id() const {
  // @@protoc_insertion_point(field_get:TestMultiKeyTable.id)
  return _internal_id();
}
inline void TestMultiKeyTable::set_id(::uint32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:TestMultiKeyTable.id)
}
inline ::uint32_t TestMultiKeyTable::_internal_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.id_;
}
inline void TestMultiKeyTable::_internal_set_id(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.id_ = value;
}

// map<string, string> tag1 = 2;
inline int TestMultiKeyTable::_internal_tag1_size() const {
  return _internal_tag1().size();
}
inline int TestMultiKeyTable::tag1_size() const {
  return _internal_tag1_size();
}
inline void TestMultiKeyTable::clear_tag1() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tag1_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& TestMultiKeyTable::_internal_tag1() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.tag1_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& TestMultiKeyTable::tag1() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:TestMultiKeyTable.tag1)
  return _internal_tag1();
}
inline ::google::protobuf::Map<std::string, std::string>* TestMultiKeyTable::_internal_mutable_tag1() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.tag1_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* TestMultiKeyTable::mutable_tag1() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:TestMultiKeyTable.tag1)
  return _internal_mutable_tag1();
}

// map<string, string> immunetag1 = 3;
inline int TestMultiKeyTable::_internal_immunetag1_size() const {
  return _internal_immunetag1().size();
}
inline int TestMultiKeyTable::immunetag1_size() const {
  return _internal_immunetag1_size();
}
inline void TestMultiKeyTable::clear_immunetag1() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.immunetag1_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& TestMultiKeyTable::_internal_immunetag1() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.immunetag1_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& TestMultiKeyTable::immunetag1() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:TestMultiKeyTable.immunetag1)
  return _internal_immunetag1();
}
inline ::google::protobuf::Map<std::string, std::string>* TestMultiKeyTable::_internal_mutable_immunetag1() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.immunetag1_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* TestMultiKeyTable::mutable_immunetag1() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:TestMultiKeyTable.immunetag1)
  return _internal_mutable_immunetag1();
}

// uint32 level = 4;
inline void TestMultiKeyTable::clear_level() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.level_ = 0u;
}
inline ::uint32_t TestMultiKeyTable::level() const {
  // @@protoc_insertion_point(field_get:TestMultiKeyTable.level)
  return _internal_level();
}
inline void TestMultiKeyTable::set_level(::uint32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:TestMultiKeyTable.level)
}
inline ::uint32_t TestMultiKeyTable::_internal_level() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.level_;
}
inline void TestMultiKeyTable::_internal_set_level(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.level_ = value;
}

// repeated .testobj1 testobj1 = 5;
inline int TestMultiKeyTable::_internal_testobj1_size() const {
  return _internal_testobj1().size();
}
inline int TestMultiKeyTable::testobj1_size() const {
  return _internal_testobj1_size();
}
inline void TestMultiKeyTable::clear_testobj1() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.testobj1_.Clear();
}
inline ::testobj1* TestMultiKeyTable::mutable_testobj1(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:TestMultiKeyTable.testobj1)
  return _internal_mutable_testobj1()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::testobj1>* TestMultiKeyTable::mutable_testobj1()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:TestMultiKeyTable.testobj1)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_testobj1();
}
inline const ::testobj1& TestMultiKeyTable::testobj1(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TestMultiKeyTable.testobj1)
  return _internal_testobj1().Get(index);
}
inline ::testobj1* TestMultiKeyTable::add_testobj1() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::testobj1* _add = _internal_mutable_testobj1()->Add();
  // @@protoc_insertion_point(field_add:TestMultiKeyTable.testobj1)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::testobj1>& TestMultiKeyTable::testobj1() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:TestMultiKeyTable.testobj1)
  return _internal_testobj1();
}
inline const ::google::protobuf::RepeatedPtrField<::testobj1>&
TestMultiKeyTable::_internal_testobj1() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.testobj1_;
}
inline ::google::protobuf::RepeatedPtrField<::testobj1>*
TestMultiKeyTable::_internal_mutable_testobj1() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.testobj1_;
}

// repeated uint32 effect = 6;
inline int TestMultiKeyTable::_internal_effect_size() const {
  return _internal_effect().size();
}
inline int TestMultiKeyTable::effect_size() const {
  return _internal_effect_size();
}
inline void TestMultiKeyTable::clear_effect() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.effect_.Clear();
}
inline ::uint32_t TestMultiKeyTable::effect(int index) const {
  // @@protoc_insertion_point(field_get:TestMultiKeyTable.effect)
  return _internal_effect().Get(index);
}
inline void TestMultiKeyTable::set_effect(int index, ::uint32_t value) {
  _internal_mutable_effect()->Set(index, value);
  // @@protoc_insertion_point(field_set:TestMultiKeyTable.effect)
}
inline void TestMultiKeyTable::add_effect(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_effect()->Add(value);
  // @@protoc_insertion_point(field_add:TestMultiKeyTable.effect)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& TestMultiKeyTable::effect() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:TestMultiKeyTable.effect)
  return _internal_effect();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* TestMultiKeyTable::mutable_effect()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:TestMultiKeyTable.effect)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_effect();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
TestMultiKeyTable::_internal_effect() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.effect_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* TestMultiKeyTable::_internal_mutable_effect() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.effect_;
}

// string stringkey = 7;
inline void TestMultiKeyTable::clear_stringkey() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.stringkey_.ClearToEmpty();
}
inline const std::string& TestMultiKeyTable::stringkey() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TestMultiKeyTable.stringkey)
  return _internal_stringkey();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TestMultiKeyTable::set_stringkey(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.stringkey_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:TestMultiKeyTable.stringkey)
}
inline std::string* TestMultiKeyTable::mutable_stringkey() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_stringkey();
  // @@protoc_insertion_point(field_mutable:TestMultiKeyTable.stringkey)
  return _s;
}
inline const std::string& TestMultiKeyTable::_internal_stringkey() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.stringkey_.Get();
}
inline void TestMultiKeyTable::_internal_set_stringkey(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.stringkey_.Set(value, GetArena());
}
inline std::string* TestMultiKeyTable::_internal_mutable_stringkey() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.stringkey_.Mutable( GetArena());
}
inline std::string* TestMultiKeyTable::release_stringkey() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:TestMultiKeyTable.stringkey)
  return _impl_.stringkey_.Release();
}
inline void TestMultiKeyTable::set_allocated_stringkey(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.stringkey_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.stringkey_.IsDefault()) {
          _impl_.stringkey_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TestMultiKeyTable.stringkey)
}

// uint32 uint32key = 8;
inline void TestMultiKeyTable::clear_uint32key() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.uint32key_ = 0u;
}
inline ::uint32_t TestMultiKeyTable::uint32key() const {
  // @@protoc_insertion_point(field_get:TestMultiKeyTable.uint32key)
  return _internal_uint32key();
}
inline void TestMultiKeyTable::set_uint32key(::uint32_t value) {
  _internal_set_uint32key(value);
  // @@protoc_insertion_point(field_set:TestMultiKeyTable.uint32key)
}
inline ::uint32_t TestMultiKeyTable::_internal_uint32key() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.uint32key_;
}
inline void TestMultiKeyTable::_internal_set_uint32key(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.uint32key_ = value;
}

// int32 in32key = 9;
inline void TestMultiKeyTable::clear_in32key() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.in32key_ = 0;
}
inline ::int32_t TestMultiKeyTable::in32key() const {
  // @@protoc_insertion_point(field_get:TestMultiKeyTable.in32key)
  return _internal_in32key();
}
inline void TestMultiKeyTable::set_in32key(::int32_t value) {
  _internal_set_in32key(value);
  // @@protoc_insertion_point(field_set:TestMultiKeyTable.in32key)
}
inline ::int32_t TestMultiKeyTable::_internal_in32key() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.in32key_;
}
inline void TestMultiKeyTable::_internal_set_in32key(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.in32key_ = value;
}

// string mstringkey = 10;
inline void TestMultiKeyTable::clear_mstringkey() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.mstringkey_.ClearToEmpty();
}
inline const std::string& TestMultiKeyTable::mstringkey() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TestMultiKeyTable.mstringkey)
  return _internal_mstringkey();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TestMultiKeyTable::set_mstringkey(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.mstringkey_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:TestMultiKeyTable.mstringkey)
}
inline std::string* TestMultiKeyTable::mutable_mstringkey() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_mstringkey();
  // @@protoc_insertion_point(field_mutable:TestMultiKeyTable.mstringkey)
  return _s;
}
inline const std::string& TestMultiKeyTable::_internal_mstringkey() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.mstringkey_.Get();
}
inline void TestMultiKeyTable::_internal_set_mstringkey(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.mstringkey_.Set(value, GetArena());
}
inline std::string* TestMultiKeyTable::_internal_mutable_mstringkey() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.mstringkey_.Mutable( GetArena());
}
inline std::string* TestMultiKeyTable::release_mstringkey() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:TestMultiKeyTable.mstringkey)
  return _impl_.mstringkey_.Release();
}
inline void TestMultiKeyTable::set_allocated_mstringkey(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.mstringkey_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.mstringkey_.IsDefault()) {
          _impl_.mstringkey_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TestMultiKeyTable.mstringkey)
}

// uint32 muint32key = 11;
inline void TestMultiKeyTable::clear_muint32key() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.muint32key_ = 0u;
}
inline ::uint32_t TestMultiKeyTable::muint32key() const {
  // @@protoc_insertion_point(field_get:TestMultiKeyTable.muint32key)
  return _internal_muint32key();
}
inline void TestMultiKeyTable::set_muint32key(::uint32_t value) {
  _internal_set_muint32key(value);
  // @@protoc_insertion_point(field_set:TestMultiKeyTable.muint32key)
}
inline ::uint32_t TestMultiKeyTable::_internal_muint32key() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.muint32key_;
}
inline void TestMultiKeyTable::_internal_set_muint32key(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.muint32key_ = value;
}

// int32 min32key = 12;
inline void TestMultiKeyTable::clear_min32key() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.min32key_ = 0;
}
inline ::int32_t TestMultiKeyTable::min32key() const {
  // @@protoc_insertion_point(field_get:TestMultiKeyTable.min32key)
  return _internal_min32key();
}
inline void TestMultiKeyTable::set_min32key(::int32_t value) {
  _internal_set_min32key(value);
  // @@protoc_insertion_point(field_set:TestMultiKeyTable.min32key)
}
inline ::int32_t TestMultiKeyTable::_internal_min32key() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.min32key_;
}
inline void TestMultiKeyTable::_internal_set_min32key(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.min32key_ = value;
}

// -------------------------------------------------------------------

// TestMultiKeyTabledData

// repeated .TestMultiKeyTable data = 1;
inline int TestMultiKeyTabledData::_internal_data_size() const {
  return _internal_data().size();
}
inline int TestMultiKeyTabledData::data_size() const {
  return _internal_data_size();
}
inline void TestMultiKeyTabledData::clear_data() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.data_.Clear();
}
inline ::TestMultiKeyTable* TestMultiKeyTabledData::mutable_data(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:TestMultiKeyTabledData.data)
  return _internal_mutable_data()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::TestMultiKeyTable>* TestMultiKeyTabledData::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:TestMultiKeyTabledData.data)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_data();
}
inline const ::TestMultiKeyTable& TestMultiKeyTabledData::data(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TestMultiKeyTabledData.data)
  return _internal_data().Get(index);
}
inline ::TestMultiKeyTable* TestMultiKeyTabledData::add_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::TestMultiKeyTable* _add = _internal_mutable_data()->Add();
  // @@protoc_insertion_point(field_add:TestMultiKeyTabledData.data)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::TestMultiKeyTable>& TestMultiKeyTabledData::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:TestMultiKeyTabledData.data)
  return _internal_data();
}
inline const ::google::protobuf::RepeatedPtrField<::TestMultiKeyTable>&
TestMultiKeyTabledData::_internal_data() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.data_;
}
inline ::google::protobuf::RepeatedPtrField<::TestMultiKeyTable>*
TestMultiKeyTabledData::_internal_mutable_data() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.data_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_testmultikey_5fconfig_2eproto_2epb_2eh
