apiVersion: v1
kind: Service
metadata:
  name: player-locator
  labels:
    app: player-locator
    tier: go-svc
spec:
  selector:
    app: player-locator
  ports:
    - name: grpc
      port: 50100
      targetPort: 50100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-locator
  labels:
    app: player-locator
    tier: go-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-locator
  template:
    metadata:
      labels:
        app: player-locator
        tier: go-svc
    spec:
      containers:
        - name: player-locator
          image: PLACEHOLDER_IMAGE
          imagePullPolicy: IfNotPresent
          env:
            - name: GOLANG_PROTOBUF_REGISTRATION_CONFLICT
              value: warn
          args: ["-f", "/app/etc/player_locator.yaml"]
          ports:
            - containerPort: 50100
              name: grpc
          volumeMounts:
            - name: svc-config
              mountPath: /app/etc
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: svc-config
          configMap:
            name: go-svc-player-locator-config
