// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: proto/login/login_service.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginC2LRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientMsgBody *LoginRequest   `protobuf:"bytes,1,opt,name=client_msg_body,json=clientMsgBody,proto3" json:"client_msg_body,omitempty"`
	SessionInfo   *SessionDetails `protobuf:"bytes,2,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
}

func (x *LoginC2LRequest) Reset() {
	*x = LoginC2LRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_login_login_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginC2LRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginC2LRequest) ProtoMessage() {}

func (x *LoginC2LRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_login_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginC2LRequest.ProtoReflect.Descriptor instead.
func (*LoginC2LRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_login_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoginC2LRequest) GetClientMsgBody() *LoginRequest {
	if x != nil {
		return x.ClientMsgBody
	}
	return nil
}

func (x *LoginC2LRequest) GetSessionInfo() *SessionDetails {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type LoginC2LResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientMsgBody *LoginResponse  `protobuf:"bytes,1,opt,name=client_msg_body,json=clientMsgBody,proto3" json:"client_msg_body,omitempty"`
	SessionInfo   *SessionDetails `protobuf:"bytes,2,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
}

func (x *LoginC2LResponse) Reset() {
	*x = LoginC2LResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_login_login_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginC2LResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginC2LResponse) ProtoMessage() {}

func (x *LoginC2LResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_login_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginC2LResponse.ProtoReflect.Descriptor instead.
func (*LoginC2LResponse) Descriptor() ([]byte, []int) {
	return file_proto_login_login_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginC2LResponse) GetClientMsgBody() *LoginResponse {
	if x != nil {
		return x.ClientMsgBody
	}
	return nil
}

func (x *LoginC2LResponse) GetSessionInfo() *SessionDetails {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type CreatePlayerC2LRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientMsgBody *CreatePlayerRequest `protobuf:"bytes,1,opt,name=client_msg_body,json=clientMsgBody,proto3" json:"client_msg_body,omitempty"`
	SessionInfo   *SessionDetails      `protobuf:"bytes,2,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
}

func (x *CreatePlayerC2LRequest) Reset() {
	*x = CreatePlayerC2LRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_login_login_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayerC2LRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerC2LRequest) ProtoMessage() {}

func (x *CreatePlayerC2LRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_login_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerC2LRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayerC2LRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_login_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePlayerC2LRequest) GetClientMsgBody() *CreatePlayerRequest {
	if x != nil {
		return x.ClientMsgBody
	}
	return nil
}

func (x *CreatePlayerC2LRequest) GetSessionInfo() *SessionDetails {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type EnterGameC2LRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientMsgBody *EnterGameRequest `protobuf:"bytes,1,opt,name=client_msg_body,json=clientMsgBody,proto3" json:"client_msg_body,omitempty"`
	SessionInfo   *SessionDetails   `protobuf:"bytes,2,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
}

func (x *EnterGameC2LRequest) Reset() {
	*x = EnterGameC2LRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_login_login_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterGameC2LRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameC2LRequest) ProtoMessage() {}

func (x *EnterGameC2LRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_login_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameC2LRequest.ProtoReflect.Descriptor instead.
func (*EnterGameC2LRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_login_service_proto_rawDescGZIP(), []int{3}
}

func (x *EnterGameC2LRequest) GetClientMsgBody() *EnterGameRequest {
	if x != nil {
		return x.ClientMsgBody
	}
	return nil
}

func (x *EnterGameC2LRequest) GetSessionInfo() *SessionDetails {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type CreatePlayerC2LResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientMsgBody *CreatePlayerResponse `protobuf:"bytes,1,opt,name=client_msg_body,json=clientMsgBody,proto3" json:"client_msg_body,omitempty"`
	SessionInfo   *SessionDetails       `protobuf:"bytes,4,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
}

func (x *CreatePlayerC2LResponse) Reset() {
	*x = CreatePlayerC2LResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_login_login_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayerC2LResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerC2LResponse) ProtoMessage() {}

func (x *CreatePlayerC2LResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_login_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerC2LResponse.ProtoReflect.Descriptor instead.
func (*CreatePlayerC2LResponse) Descriptor() ([]byte, []int) {
	return file_proto_login_login_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePlayerC2LResponse) GetClientMsgBody() *CreatePlayerResponse {
	if x != nil {
		return x.ClientMsgBody
	}
	return nil
}

func (x *CreatePlayerC2LResponse) GetSessionInfo() *SessionDetails {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type EnterGameC2LResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientMsgBody *EnterGameResponse `protobuf:"bytes,1,opt,name=client_msg_body,json=clientMsgBody,proto3" json:"client_msg_body,omitempty"`
	SessionInfo   *SessionDetails    `protobuf:"bytes,4,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
}

func (x *EnterGameC2LResponse) Reset() {
	*x = EnterGameC2LResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_login_login_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterGameC2LResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameC2LResponse) ProtoMessage() {}

func (x *EnterGameC2LResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_login_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameC2LResponse.ProtoReflect.Descriptor instead.
func (*EnterGameC2LResponse) Descriptor() ([]byte, []int) {
	return file_proto_login_login_service_proto_rawDescGZIP(), []int{5}
}

func (x *EnterGameC2LResponse) GetClientMsgBody() *EnterGameResponse {
	if x != nil {
		return x.ClientMsgBody
	}
	return nil
}

func (x *EnterGameC2LResponse) GetSessionInfo() *SessionDetails {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type LoginNodeDisconnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId uint64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *LoginNodeDisconnectRequest) Reset() {
	*x = LoginNodeDisconnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_login_login_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginNodeDisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginNodeDisconnectRequest) ProtoMessage() {}

func (x *LoginNodeDisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_login_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginNodeDisconnectRequest.ProtoReflect.Descriptor instead.
func (*LoginNodeDisconnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_login_service_proto_rawDescGZIP(), []int{6}
}

func (x *LoginNodeDisconnectRequest) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type LeaveGameC2LRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId uint64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *LeaveGameC2LRequest) Reset() {
	*x = LeaveGameC2LRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_login_login_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveGameC2LRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGameC2LRequest) ProtoMessage() {}

func (x *LeaveGameC2LRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_login_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGameC2LRequest.ProtoReflect.Descriptor instead.
func (*LeaveGameC2LRequest) Descriptor() ([]byte, []int) {
	return file_proto_login_login_service_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveGameC2LRequest) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

var File_proto_login_login_service_proto protoreflect.FileDescriptor

var file_proto_login_login_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2f, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x70, 0x62, 0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x63, 0x32, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x0f, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x43, 0x32, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35,
	0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73,
	0x67, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x32, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0b, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x7e, 0x0a, 0x10, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x43, 0x32, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a,
	0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73,
	0x67, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x32, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0b, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x16, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x32, 0x4c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d,
	0x73, 0x67, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x32, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x13, 0x45, 0x6e, 0x74, 0x65, 0x72,
	0x47, 0x61, 0x6d, 0x65, 0x43, 0x32, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39,
	0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x32, 0x0a, 0x0c, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x8c, 0x01,
	0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x32,
	0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x32, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x86, 0x01, 0x0a,
	0x14, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x32, 0x4c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x6d, 0x73, 0x67, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64,
	0x79, 0x12, 0x32, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x3b, 0x0a, 0x1a, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x6f,
	0x64, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x34, 0x0a, 0x13, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43,
	0x32, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x32, 0xdc, 0x02, 0x0a, 0x11, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x3c,
	0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x70,
	0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x32, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x43, 0x32, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x43, 0x32, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x43, 0x32, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x48, 0x0a, 0x09, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65,
	0x43, 0x32, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x32,
	0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x70, 0x62,
	0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x32, 0x4c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x39, 0x0a, 0x0a,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x23, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x69,
	0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x09, 0x5a, 0x07, 0x70, 0x62, 0x2f, 0x67, 0x61,
	0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_login_login_service_proto_rawDescOnce sync.Once
	file_proto_login_login_service_proto_rawDescData = file_proto_login_login_service_proto_rawDesc
)

func file_proto_login_login_service_proto_rawDescGZIP() []byte {
	file_proto_login_login_service_proto_rawDescOnce.Do(func() {
		file_proto_login_login_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_login_login_service_proto_rawDescData)
	})
	return file_proto_login_login_service_proto_rawDescData
}

var file_proto_login_login_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_login_login_service_proto_goTypes = []any{
	(*LoginC2LRequest)(nil),            // 0: loginpb.LoginC2LRequest
	(*LoginC2LResponse)(nil),           // 1: loginpb.LoginC2LResponse
	(*CreatePlayerC2LRequest)(nil),     // 2: loginpb.CreatePlayerC2LRequest
	(*EnterGameC2LRequest)(nil),        // 3: loginpb.EnterGameC2LRequest
	(*CreatePlayerC2LResponse)(nil),    // 4: loginpb.CreatePlayerC2LResponse
	(*EnterGameC2LResponse)(nil),       // 5: loginpb.EnterGameC2LResponse
	(*LoginNodeDisconnectRequest)(nil), // 6: loginpb.LoginNodeDisconnectRequest
	(*LeaveGameC2LRequest)(nil),        // 7: loginpb.LeaveGameC2LRequest
	(*LoginRequest)(nil),               // 8: LoginRequest
	(*SessionDetails)(nil),             // 9: SessionDetails
	(*LoginResponse)(nil),              // 10: LoginResponse
	(*CreatePlayerRequest)(nil),        // 11: CreatePlayerRequest
	(*EnterGameRequest)(nil),           // 12: EnterGameRequest
	(*CreatePlayerResponse)(nil),       // 13: CreatePlayerResponse
	(*EnterGameResponse)(nil),          // 14: EnterGameResponse
	(*Empty)(nil),                      // 15: Empty
}
var file_proto_login_login_service_proto_depIdxs = []int32{
	8,  // 0: loginpb.LoginC2LRequest.client_msg_body:type_name -> LoginRequest
	9,  // 1: loginpb.LoginC2LRequest.session_info:type_name -> SessionDetails
	10, // 2: loginpb.LoginC2LResponse.client_msg_body:type_name -> LoginResponse
	9,  // 3: loginpb.LoginC2LResponse.session_info:type_name -> SessionDetails
	11, // 4: loginpb.CreatePlayerC2LRequest.client_msg_body:type_name -> CreatePlayerRequest
	9,  // 5: loginpb.CreatePlayerC2LRequest.session_info:type_name -> SessionDetails
	12, // 6: loginpb.EnterGameC2LRequest.client_msg_body:type_name -> EnterGameRequest
	9,  // 7: loginpb.EnterGameC2LRequest.session_info:type_name -> SessionDetails
	13, // 8: loginpb.CreatePlayerC2LResponse.client_msg_body:type_name -> CreatePlayerResponse
	9,  // 9: loginpb.CreatePlayerC2LResponse.session_info:type_name -> SessionDetails
	14, // 10: loginpb.EnterGameC2LResponse.client_msg_body:type_name -> EnterGameResponse
	9,  // 11: loginpb.EnterGameC2LResponse.session_info:type_name -> SessionDetails
	0,  // 12: loginpb.ClientPlayerLogin.Login:input_type -> loginpb.LoginC2LRequest
	2,  // 13: loginpb.ClientPlayerLogin.CreatePlayer:input_type -> loginpb.CreatePlayerC2LRequest
	3,  // 14: loginpb.ClientPlayerLogin.EnterGame:input_type -> loginpb.EnterGameC2LRequest
	7,  // 15: loginpb.ClientPlayerLogin.LeaveGame:input_type -> loginpb.LeaveGameC2LRequest
	6,  // 16: loginpb.ClientPlayerLogin.Disconnect:input_type -> loginpb.LoginNodeDisconnectRequest
	1,  // 17: loginpb.ClientPlayerLogin.Login:output_type -> loginpb.LoginC2LResponse
	4,  // 18: loginpb.ClientPlayerLogin.CreatePlayer:output_type -> loginpb.CreatePlayerC2LResponse
	5,  // 19: loginpb.ClientPlayerLogin.EnterGame:output_type -> loginpb.EnterGameC2LResponse
	15, // 20: loginpb.ClientPlayerLogin.LeaveGame:output_type -> Empty
	15, // 21: loginpb.ClientPlayerLogin.Disconnect:output_type -> Empty
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_login_login_service_proto_init() }
func file_proto_login_login_service_proto_init() {
	if File_proto_login_login_service_proto != nil {
		return
	}
	file_proto_common_empty_proto_init()
	file_proto_common_c2gate_proto_init()
	file_proto_common_session_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_login_login_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LoginC2LRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_login_login_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LoginC2LResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_login_login_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePlayerC2LRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_login_login_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*EnterGameC2LRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_login_login_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePlayerC2LResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_login_login_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*EnterGameC2LResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_login_login_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*LoginNodeDisconnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_login_login_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*LeaveGameC2LRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_login_login_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_login_login_service_proto_goTypes,
		DependencyIndexes: file_proto_login_login_service_proto_depIdxs,
		MessageInfos:      file_proto_login_login_service_proto_msgTypes,
	}.Build()
	File_proto_login_login_service_proto = out.File
	file_proto_login_login_service_proto_rawDesc = nil
	file_proto_login_login_service_proto_goTypes = nil
	file_proto_login_login_service_proto_depIdxs = nil
}
