// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: proto/service/cpp/rpc/centre/centre_scene.proto

package centre

import (
	common "chat/proto/proto/common"
	_ "github.com/luyuancpp/protooption"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterSceneRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	SceneNodeId   uint32                        `protobuf:"varint,1,opt,name=scene_node_id,json=sceneNodeId,proto3" json:"scene_node_id,omitempty"`
	ScenesInfo    []*common.RoomInfoPBComponent `protobuf:"bytes,2,rep,name=scenes_info,json=scenesInfo,proto3" json:"scenes_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSceneRequest) Reset() {
	*x = RegisterSceneRequest{}
	mi := &file_proto_service_cpp_rpc_centre_centre_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSceneRequest) ProtoMessage() {}

func (x *RegisterSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_cpp_rpc_centre_centre_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSceneRequest.ProtoReflect.Descriptor instead.
func (*RegisterSceneRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterSceneRequest) GetSceneNodeId() uint32 {
	if x != nil {
		return x.SceneNodeId
	}
	return 0
}

func (x *RegisterSceneRequest) GetScenesInfo() []*common.RoomInfoPBComponent {
	if x != nil {
		return x.ScenesInfo
	}
	return nil
}

type RegisterSceneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSceneResponse) Reset() {
	*x = RegisterSceneResponse{}
	mi := &file_proto_service_cpp_rpc_centre_centre_scene_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSceneResponse) ProtoMessage() {}

func (x *RegisterSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_cpp_rpc_centre_centre_scene_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSceneResponse.ProtoReflect.Descriptor instead.
func (*RegisterSceneResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDescGZIP(), []int{1}
}

type UnRegisterSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneNodeId   uint32                 `protobuf:"varint,1,opt,name=scene_node_id,json=sceneNodeId,proto3" json:"scene_node_id,omitempty"`
	Scene         uint32                 `protobuf:"varint,2,opt,name=scene,proto3" json:"scene,omitempty"`
	Reason        uint32                 `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnRegisterSceneRequest) Reset() {
	*x = UnRegisterSceneRequest{}
	mi := &file_proto_service_cpp_rpc_centre_centre_scene_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnRegisterSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterSceneRequest) ProtoMessage() {}

func (x *UnRegisterSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_cpp_rpc_centre_centre_scene_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterSceneRequest.ProtoReflect.Descriptor instead.
func (*UnRegisterSceneRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDescGZIP(), []int{2}
}

func (x *UnRegisterSceneRequest) GetSceneNodeId() uint32 {
	if x != nil {
		return x.SceneNodeId
	}
	return 0
}

func (x *UnRegisterSceneRequest) GetScene() uint32 {
	if x != nil {
		return x.Scene
	}
	return 0
}

func (x *UnRegisterSceneRequest) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

var File_proto_service_cpp_rpc_centre_centre_scene_proto protoreflect.FileDescriptor

const file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDesc = "" +
	"\n" +
	"/proto/service/cpp/rpc/centre/centre_scene.proto\x1a+proto/service/go/grpc/db/proto_option.proto\x1a\x18proto/common/empty.proto\x1a\x19proto/common/common.proto\"q\n" +
	"\x14RegisterSceneRequest\x12\"\n" +
	"\rscene_node_id\x18\x01 \x01(\rR\vsceneNodeId\x125\n" +
	"\vscenes_info\x18\x02 \x03(\v2\x14.RoomInfoPBComponentR\n" +
	"scenesInfo\"\x17\n" +
	"\x15RegisterSceneResponse\"j\n" +
	"\x16UnRegisterSceneRequest\x12\"\n" +
	"\rscene_node_id\x18\x01 \x01(\rR\vsceneNodeId\x12\x14\n" +
	"\x05scene\x18\x02 \x01(\rR\x05scene\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\rR\x06reason2\x81\x01\n" +
	"\vCentreScene\x12>\n" +
	"\rRegisterScene\x12\x15.RegisterSceneRequest\x1a\x16.RegisterSceneResponse\x122\n" +
	"\x0fUnRegisterScene\x12\x17.UnRegisterSceneRequest\x1a\x06.EmptyB7\x98\xd4a\x04Z.chat/proto/proto/service/cpp/rpc/centre;centre\x80\x01\x01b\x06proto3"

var (
	file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDescOnce sync.Once
	file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDescData []byte
)

func file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDescGZIP() []byte {
	file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDescOnce.Do(func() {
		file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDesc), len(file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDesc)))
	})
	return file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDescData
}

var file_proto_service_cpp_rpc_centre_centre_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_service_cpp_rpc_centre_centre_scene_proto_goTypes = []any{
	(*RegisterSceneRequest)(nil),       // 0: RegisterSceneRequest
	(*RegisterSceneResponse)(nil),      // 1: RegisterSceneResponse
	(*UnRegisterSceneRequest)(nil),     // 2: UnRegisterSceneRequest
	(*common.RoomInfoPBComponent)(nil), // 3: RoomInfoPBComponent
	(*common.Empty)(nil),               // 4: Empty
}
var file_proto_service_cpp_rpc_centre_centre_scene_proto_depIdxs = []int32{
	3, // 0: RegisterSceneRequest.scenes_info:type_name -> RoomInfoPBComponent
	0, // 1: CentreScene.RegisterScene:input_type -> RegisterSceneRequest
	2, // 2: CentreScene.UnRegisterScene:input_type -> UnRegisterSceneRequest
	1, // 3: CentreScene.RegisterScene:output_type -> RegisterSceneResponse
	4, // 4: CentreScene.UnRegisterScene:output_type -> Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_service_cpp_rpc_centre_centre_scene_proto_init() }
func file_proto_service_cpp_rpc_centre_centre_scene_proto_init() {
	if File_proto_service_cpp_rpc_centre_centre_scene_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDesc), len(file_proto_service_cpp_rpc_centre_centre_scene_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_cpp_rpc_centre_centre_scene_proto_goTypes,
		DependencyIndexes: file_proto_service_cpp_rpc_centre_centre_scene_proto_depIdxs,
		MessageInfos:      file_proto_service_cpp_rpc_centre_centre_scene_proto_msgTypes,
	}.Build()
	File_proto_service_cpp_rpc_centre_centre_scene_proto = out.File
	file_proto_service_cpp_rpc_centre_centre_scene_proto_goTypes = nil
	file_proto_service_cpp_rpc_centre_centre_scene_proto_depIdxs = nil
}
