# constants.py

# 常量定义
DESIGNER = "designer"
CONSTANTS_NAME = "constants_name"
SERVER_TYPE = "server"
COMMON_TYPE = "common"
SERVER_GEN_TYPE = [SERVER_TYPE, COMMON_TYPE]
PROJECT_DIR = "../../../"
PROJECT_GENERATED_JSON_DIR = PROJECT_DIR + "generated_tables/"
PROJECT_GENERATED_CODE_DIR = PROJECT_DIR + "generated_code/"
XLSX_DIR = PROJECT_DIR + "data_tables/"

GENERATOR_TABLE_INDEX_DIR = PROJECT_GENERATED_CODE_DIR + "cpp/cpp_table_id_bit_index/"
GENERATOR_CONSTANTS_NAME_DIR = PROJECT_GENERATED_CODE_DIR + "cpp_table_id_constants_name/"

GENERATOR_TABLE_INDEX_GO_DIR = PROJECT_GENERATED_CODE_DIR + "go/go_table_id_bit_index/"
GENERATOR_CONSTANTS_NAME_GO_DIR = PROJECT_GENERATED_CODE_DIR + "go/go_table_id_constants_name/"


PROTO_DIR =  PROJECT_GENERATED_CODE_DIR + "proto/"

PROJECT_GENERATED_CODE_PROTO_TIP_DIR = PROJECT_DIR + "generated_code/proto/tip/"

PROJECT_OPERATOR_XLSX = XLSX_DIR + 'operator/Operator.xlsx'
PROJECT_GENERATED_CODE_PROTO_OPERATOR_DIR = PROJECT_DIR + "proto/operator/"


GENERATOR_STORAGE_DIR = "state/"
GENERATOR_STORAGE_OPERATOR_DIR = GENERATOR_STORAGE_DIR + "operator/"

GENERATOR_TABLE_INDEX_MAPPING_DIR = GENERATOR_STORAGE_DIR + "mapping/table_index_mapping/"
GENERATOR_TIP_MAPPING_DIR = GENERATOR_STORAGE_DIR + "mapping/tip_enum_ids/"