// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: proto/service/cpp/rpc/scene/player_state_attribute_sync.proto

package scene

import (
	_ "github.com/luyuancpp/protooption"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "login/proto/proto/common"
	component "login/proto/proto/logic/component"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息定义，用于同步实体的基础属性增量
type ActorBaseAttributesS2C struct {
	state            protoimpl.MessageState                 `protogen:"open.v1"`
	EntityId         uint64                                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // 实体的唯一ID
	Transform        *component.Transform                   `protobuf:"bytes,2,opt,name=transform,proto3" json:"transform,omitempty"`                // 速度信息
	Velocity         *component.Velocity                    `protobuf:"bytes,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
	CombatStateFlags *component.CombatStateFlagsPbComponent `protobuf:"bytes,4,opt,name=combat_state_flags,json=combatStateFlags,proto3" json:"combat_state_flags,omitempty"` //战斗状态
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActorBaseAttributesS2C) Reset() {
	*x = ActorBaseAttributesS2C{}
	mi := &file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorBaseAttributesS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorBaseAttributesS2C) ProtoMessage() {}

func (x *ActorBaseAttributesS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorBaseAttributesS2C.ProtoReflect.Descriptor instead.
func (*ActorBaseAttributesS2C) Descriptor() ([]byte, []int) {
	return file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDescGZIP(), []int{0}
}

func (x *ActorBaseAttributesS2C) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *ActorBaseAttributesS2C) GetTransform() *component.Transform {
	if x != nil {
		return x.Transform
	}
	return nil
}

func (x *ActorBaseAttributesS2C) GetVelocity() *component.Velocity {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *ActorBaseAttributesS2C) GetCombatStateFlags() *component.CombatStateFlagsPbComponent {
	if x != nil {
		return x.CombatStateFlags
	}
	return nil
}

// 各种帧率同步消息
type AttributeDelta2FramesS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // 实体的唯一ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeDelta2FramesS2C) Reset() {
	*x = AttributeDelta2FramesS2C{}
	mi := &file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeDelta2FramesS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDelta2FramesS2C) ProtoMessage() {}

func (x *AttributeDelta2FramesS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDelta2FramesS2C.ProtoReflect.Descriptor instead.
func (*AttributeDelta2FramesS2C) Descriptor() ([]byte, []int) {
	return file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDescGZIP(), []int{1}
}

func (x *AttributeDelta2FramesS2C) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

type AttributeDelta5FramesS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // 实体的唯一ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeDelta5FramesS2C) Reset() {
	*x = AttributeDelta5FramesS2C{}
	mi := &file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeDelta5FramesS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDelta5FramesS2C) ProtoMessage() {}

func (x *AttributeDelta5FramesS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDelta5FramesS2C.ProtoReflect.Descriptor instead.
func (*AttributeDelta5FramesS2C) Descriptor() ([]byte, []int) {
	return file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDescGZIP(), []int{2}
}

func (x *AttributeDelta5FramesS2C) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

type AttributeDelta10FramesS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // 实体的唯一ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeDelta10FramesS2C) Reset() {
	*x = AttributeDelta10FramesS2C{}
	mi := &file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeDelta10FramesS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDelta10FramesS2C) ProtoMessage() {}

func (x *AttributeDelta10FramesS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDelta10FramesS2C.ProtoReflect.Descriptor instead.
func (*AttributeDelta10FramesS2C) Descriptor() ([]byte, []int) {
	return file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDescGZIP(), []int{3}
}

func (x *AttributeDelta10FramesS2C) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

type AttributeDelta30FramesS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // 实体的唯一ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeDelta30FramesS2C) Reset() {
	*x = AttributeDelta30FramesS2C{}
	mi := &file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeDelta30FramesS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDelta30FramesS2C) ProtoMessage() {}

func (x *AttributeDelta30FramesS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDelta30FramesS2C.ProtoReflect.Descriptor instead.
func (*AttributeDelta30FramesS2C) Descriptor() ([]byte, []int) {
	return file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDescGZIP(), []int{4}
}

func (x *AttributeDelta30FramesS2C) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

type AttributeDelta60FramesS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // 实体的唯一ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeDelta60FramesS2C) Reset() {
	*x = AttributeDelta60FramesS2C{}
	mi := &file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeDelta60FramesS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDelta60FramesS2C) ProtoMessage() {}

func (x *AttributeDelta60FramesS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDelta60FramesS2C.ProtoReflect.Descriptor instead.
func (*AttributeDelta60FramesS2C) Descriptor() ([]byte, []int) {
	return file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDescGZIP(), []int{5}
}

func (x *AttributeDelta60FramesS2C) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

var File_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto protoreflect.FileDescriptor

const file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDesc = "" +
	"\n" +
	"=proto/service/cpp/rpc/scene/player_state_attribute_sync.proto\x1a+proto/service/go/grpc/db/proto_option.proto\x1a&proto/logic/component/actor_comp.proto\x1a\x18proto/common/empty.proto\x1a6proto/logic/component/actor_attribute_state_comp.proto\"\xd2\x01\n" +
	"\x16ActorBaseAttributesS2C\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12(\n" +
	"\ttransform\x18\x02 \x01(\v2\n" +
	".TransformR\ttransform\x12%\n" +
	"\bvelocity\x18\x03 \x01(\v2\t.VelocityR\bvelocity\x12J\n" +
	"\x12combat_state_flags\x18\x04 \x01(\v2\x1c.CombatStateFlagsPbComponentR\x10combatStateFlags\"7\n" +
	"\x18AttributeDelta2FramesS2C\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\"7\n" +
	"\x18AttributeDelta5FramesS2C\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\"8\n" +
	"\x19AttributeDelta10FramesS2C\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\"8\n" +
	"\x19AttributeDelta30FramesS2C\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\"8\n" +
	"\x19AttributeDelta60FramesS2C\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId2\xfb\x02\n" +
	"\x0fScenePlayerSync\x124\n" +
	"\x11SyncBaseAttribute\x12\x17.ActorBaseAttributesS2C\x1a\x06.Empty\x129\n" +
	"\x14SyncAttribute2Frames\x12\x19.AttributeDelta2FramesS2C\x1a\x06.Empty\x129\n" +
	"\x14SyncAttribute5Frames\x12\x19.AttributeDelta5FramesS2C\x1a\x06.Empty\x12;\n" +
	"\x15SyncAttribute10Frames\x12\x1a.AttributeDelta10FramesS2C\x1a\x06.Empty\x12;\n" +
	"\x15SyncAttribute30Frames\x12\x1a.AttributeDelta30FramesS2C\x1a\x06.Empty\x12;\n" +
	"\x15SyncAttribute60Frames\x12\x1a.AttributeDelta60FramesS2C\x1a\x06.Empty\x1a\x05\x80\xa8\xc3\x01\x01B6\x98\xd4a\x03Z-login/proto/proto/service/cpp/rpc/scene;scene\x80\x01\x01b\x06proto3"

var (
	file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDescOnce sync.Once
	file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDescData []byte
)

func file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDescGZIP() []byte {
	file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDescOnce.Do(func() {
		file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDesc), len(file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDesc)))
	})
	return file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDescData
}

var file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_goTypes = []any{
	(*ActorBaseAttributesS2C)(nil),                // 0: ActorBaseAttributesS2C
	(*AttributeDelta2FramesS2C)(nil),              // 1: AttributeDelta2FramesS2C
	(*AttributeDelta5FramesS2C)(nil),              // 2: AttributeDelta5FramesS2C
	(*AttributeDelta10FramesS2C)(nil),             // 3: AttributeDelta10FramesS2C
	(*AttributeDelta30FramesS2C)(nil),             // 4: AttributeDelta30FramesS2C
	(*AttributeDelta60FramesS2C)(nil),             // 5: AttributeDelta60FramesS2C
	(*component.Transform)(nil),                   // 6: Transform
	(*component.Velocity)(nil),                    // 7: Velocity
	(*component.CombatStateFlagsPbComponent)(nil), // 8: CombatStateFlagsPbComponent
	(*common.Empty)(nil),                          // 9: Empty
}
var file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_depIdxs = []int32{
	6, // 0: ActorBaseAttributesS2C.transform:type_name -> Transform
	7, // 1: ActorBaseAttributesS2C.velocity:type_name -> Velocity
	8, // 2: ActorBaseAttributesS2C.combat_state_flags:type_name -> CombatStateFlagsPbComponent
	0, // 3: ScenePlayerSync.SyncBaseAttribute:input_type -> ActorBaseAttributesS2C
	1, // 4: ScenePlayerSync.SyncAttribute2Frames:input_type -> AttributeDelta2FramesS2C
	2, // 5: ScenePlayerSync.SyncAttribute5Frames:input_type -> AttributeDelta5FramesS2C
	3, // 6: ScenePlayerSync.SyncAttribute10Frames:input_type -> AttributeDelta10FramesS2C
	4, // 7: ScenePlayerSync.SyncAttribute30Frames:input_type -> AttributeDelta30FramesS2C
	5, // 8: ScenePlayerSync.SyncAttribute60Frames:input_type -> AttributeDelta60FramesS2C
	9, // 9: ScenePlayerSync.SyncBaseAttribute:output_type -> Empty
	9, // 10: ScenePlayerSync.SyncAttribute2Frames:output_type -> Empty
	9, // 11: ScenePlayerSync.SyncAttribute5Frames:output_type -> Empty
	9, // 12: ScenePlayerSync.SyncAttribute10Frames:output_type -> Empty
	9, // 13: ScenePlayerSync.SyncAttribute30Frames:output_type -> Empty
	9, // 14: ScenePlayerSync.SyncAttribute60Frames:output_type -> Empty
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_init() }
func file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_init() {
	if File_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDesc), len(file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_goTypes,
		DependencyIndexes: file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_depIdxs,
		MessageInfos:      file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_msgTypes,
	}.Build()
	File_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto = out.File
	file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_goTypes = nil
	file_proto_service_cpp_rpc_scene_player_state_attribute_sync_proto_depIdxs = nil
}
