# Etcd 配置，存储服务发现相关信息
Etcd:
  Hosts:
    - "127.0.0.1:2379"  # Etcd 服务的主机地址
  KeepaliveInterval: 20  # 保活间隔（秒）
  NodeTTLSeconds: 60    # 节点的TTL时间，单位为秒。比如这里设置为60秒

# 日志配置，控制日志输出的级别
LogLevel: 1  # 1表示info级别日志

# 服务列表，存储所有需要连接的服务
services:
  - name: "service1"
    url: "http://localhost:8081/v1/health/service/service1"  # 服务1的健康检查URL
  - name: "service2"
    url: "http://localhost:8082/v1/catalog/service/service2"  # 服务2的健康检查URL

# 独立配置 deployservice.rpc 前缀
deployservice_prefix: "deployservice.rpc"

# 其他服务的服务发现前缀
service_discovery_prefixes:
  - "sceneservice.rpc"
  - "gateservice.rpc"
  - "centreservice.rpc"
  - "loginservice.rpc"
